### ISSUE TITLE
SAMPSTAT is missing

### ISSUE THREAD

**Issue by cjvanlissa** [michaelhallquist/MplusAutomation#100]
I can't get readModels() to read the SAMPSTAT part of the output. I believe it's because the header "SAMPLE STATISTICS" is sometimes printed twice in the output file, and readModels only parses the three empty lines between these double headers. 

Pull request #98 contains a simple, dirty bug fix that checks if the section consists of only empty lines, and if so, tries to grab the relevant lines a different way before parsing them as usual.

**Comment by ddueber** [comment]
I have a similar problem with one of my output files. I am attaching the file here so that you can replicate the bug

[mplus1010.zip](https://github.com/michaelhallquist/MplusAutomation/files/3575971/mplus1010.zip)

**Comment by sda030** [comment]
Similar issue, as error arises when the headers are "UNIVARIATE PROPORTIONS AND COUNTS FOR CATEGORICAL VARIABLES" and "UNIVARIATE SAMPLE STATISTICS". Why can't Mplus be a bit more consistent?..
`Reading model:  ord_b_hms_n.out 
Error extracting SAMPSTAT in output file: ord_b_hms_n.out
<simpleError in apply(out[, -1], 2, as.numeric): dim(X) must have a positive length>`
[ord_a_dig_b.txt](https://github.com/michaelhallquist/MplusAutomation/files/4419966/ord_a_dig_b.txt)

**Comment by michaelhallquist** [comment]
Hi there,

Thanks for these details. I've now updated the parser for SAMPSTAT to handle multiple-groups outputs. I've also verified that both of the outputs provided with this issue are now handled properly within readModels. I'm sure there may be other occasions where SAMPSTAT breaks down, but I have now run the updated code against most of the Mplus user's guide and have not encountered problems. I'll close this for now, but feel free to re-open if you have a new output file that is failing.

Michael
