### ISSUE TITLE
Adding number of latent classes to results$parameters$probability.scale and results$summaries

### ISSUE THREAD

**Issue by sda030** [michaelhallquist/MplusAutomation#103]
Just suggesting two simple enhancements. 1) adding variable specifying which latent class the probability.scale parameter belongs to, and 2) number of latent classes in summaries. Both should be easy enhancements (though admittedly not important as user can add manually). For 1), I suggest a simple rep(1:n_classes, each=n_unique_parameters*n_categories), which is logically faulty but assumption is pretty safe. 

Keep up great work!

**Comment by michaelhallquist** [comment]
These suggestions have now been implemented in the development version of the package. The omission of classes from the probability scale was just a glitch in column reordering that accidentally dropped this column.
