### ISSUE TITLE
Can NOT extract out PSR (Potential Scale Reduction) value from Mplus output for further analysis using Mplusautomation package

### ISSUE THREAD

**Issue by mhwxl2015** [michaelhallquist/MplusAutomation#108]
Dr Michael,
I can NOT extract PSR (Potential Scale Reduction) value out from the Mplus output for further analysis.
I really saw a column of  PSR values from the Mplus output but I can't take it out using Mplusautomation package.

When I load the package and typed r-code like this, what I found is 0*0 data frame.
a<-readModels("sem5.bay1.out")
a$tech8$psr 

Thanks for your kindly help!

Best,

F.

**Comment by michaelhallquist** [comment]
This has already been fixed in the development version of the package. Please install that and, if the problem persists, you can re-open this issue, attaching the code and output used to generate the problem.

Thanks,
Michael

**Comment by mhwxl2015** [comment]
Dr Michael,
Thank you very much!

Best,

Hao
________________________________
