### ISSUE TITLE
Mplusautomation package just extract parital PSR(Potential scale Reduction) values out of the Mplus output using Tech8.

### ISSUE THREAD

**Issue by mhwxl2015** [michaelhallquist/MplusAutomation#109]
Dr Michael,
Good afternoon. I used Mplusautomation package (version 0.7.3) to run Bayesian analysis and found it can extract the first part PSR values out of the Mplus output.
There are two parts PSR values: the first part is for the computation of PPPP value and the second part is for the model estimation.
What I need is the complete PSR values.

Following is the r-command I used:
a<-readModels("sem5.bay2.out")
a$results$tech8$psr

Could you please help me to fix this problem? I appreciate your kindly help!

Best,
F.

**Comment by michaelhallquist** [comment]
Hi there,

I just implemented a fork in the PSR parsing that will separate the pppp section into $tech8$psr_pppp. The regular model PSR will still show up in $tech8$psr. If you install the development version of the package, you should see this fix, and I verified that it works with your output.

Best,
Michael

**Comment by mhwxl2015** [comment]
Dr Michael,
Thank you!
It is really solved!

Best Regards,

Hao
________________________________
