### ISSUE TITLE
The function "getSavedata_Bparams" doesn't work after running Bayesian Analysis

### ISSUE THREAD

**Issue by mhwxl2015** [michaelhallquist/MplusAutomation#111]
Dr Michael,
Good afternoon. I am running a Bayesian analysis model  and trying to save the parameter estimates using the function above via MplusAutomation package version 0.7.3.
Attached is the mplus output file.

My code is as follows:
library(MplusAutomation)
data10132019<-getSavedata_Bparams("01_bayessem01.out", discardBurnin=T)

The error message in the red said "Error in getSection("^\\s*SAVEDATA INFORMATION\\s*$", outfiletext) : 
  Standard headers not parsed".

I don't know whether this function is dead or could you please help me to fix this problem?

Thank you very much!

**Comment by michaelhallquist** [comment]
That function has been removed/deprecated. I had forgotten to add the message, but you can get the same functionality using  readModels("nameofMplusoutfile.out", what="bparameters")$bparameters,

Best,
Michael
