### ISSUE TITLE
Trouble installing the package

### ISSUE THREAD

**Issue by squeezal** [michaelhallquist/MplusAutomation#112]
I'm trying to install the package but it keeps getting an ERROR related to compilation failed for package ‘data.table’.  The MplusAutomation package then fails to install. 
I am using Rstudio Version 1.2.1578.  I'd appreciate any advice!

**Comment by squeezal** [comment]
I'm a little disappointed that I hadn't heard back from anyone one this question!!  But it's OK because I think I may be OK now.  I tried installing the package in a slightly different way.  I get a couple of error messages still, but it seems to be working. Fingers crossed!

**Comment by michaelhallquist** [comment]
In general, problems with compiling dependencies of a package are not the fault of the package itself. So, I suspect there is some problem with your compilation environment that affects data.table. But without seeing the exact code, output, and environment you're using to install, I can't say whether it has something to do with MplusAutomation.

Michael
