### ISSUE TITLE
The error in R package 

### ISSUE THREAD

**Issue by mroshanaei** [michaelhallquist/MplusAutomation#113]
Hi, 

I'm trying the following code in R package. It's working in Mplus. But I will get the following message in R. 
Any idea why I'm getting the following error. 

Thanks,
Mahnaz 

Error in R package: 

Wrote model to: montecarlo.inp

Running model: montecarlo.inp 
System command: cd "." && "/Applications/Mplus/mplus" "montecarlo.inp" 
Reading model:  montecarlo.out 
Warning message:
In runModels(target = modelout, Mplus_command = Mplus_command, logFile = NULL) :
  Mplus returned error code: 1, for model: montecarlo.inp

 MPLUS code:
MONTECARLO:
 NAMES ARE Stressed lag_Stressed NgDisRatio PsDisRatio; ! a)

 NOBSERVATIONS = 67200 ; ! b)
 NCSIZES = 1;
 ! let sub represent the range of the number of subjects
 NCSIZE = 1 ;
 CSIZES =  800 (84) ; ! c)
 SEED = 2020 ; ! d)
 NREPS = 100; ! e)
 WITHIN = lag_Stressed NgDisRatio PsDisRatio;! g)
 !BETWEEN = ; ! h)
 !PATMISS = Stressed(0.1) lag_Stressed(0.2) NgDisRatio(0.5) PsDisRatio(.2);
 !PATPROBS = 1; ! f)
 MISSING = Stressed; 
ANALYSIS:
TYPE = TWOLEVEL RANDOM; ! i)
!ALGORITHM=INTEGRATION;

!INTEGRATION = MONTECARLO;
MODEL POPULATION: ! j)
%WITHIN% ! k)
slope | Stressed ON NgDisRatio; ! define the random slope of NgDisRatio main effect
Stressed ON lag_Stressed*0.54957    ; ! lag.Stressed main effect
Stressed ON PsDisRatio*-0.18219    ; ! PsDisRatio main effect
[lag_Stressed *3.131349] ; lag_Stressed *1.432338; !(lag.stressed Mean and Var)
[PsDisRatio *0.3961094]; PsDisRatio *0.2019174; !(PsDisRatio Mean and Var)
[NgDisRatio *0.3064143]; NgDisRatio *0.1930179; !(NgDisRatio Mean and Var)
Stressed*0.87; ! residual variance of Stressed
%BETWEEN% ! l)
[Stressed*1.312]; Stressed* 0.046 ; !intercept estimate 1.312 and variance 0.046)
[slope*0.38058]; slope*0.01574; ! NgDisRatio slope (0.38) and variance (0.015)
MODEL MISSING:
 [Stressed@-2];
 Stressed ON lag_Stressed*.4 NgDisRatio*.5 PsDisRatio*.5;
MODEL: ! m)
%WITHIN% ! k)
slope | Stressed ON NgDisRatio; ! define the random slope of NgDisRatio main effect
Stressed ON lag_Stressed*0.54957    ; ! lag.Stressed main effect
Stressed ON PsDisRatio*-0.18219    ; ! PsDisRatio main effect
[lag_Stressed *3.131349] ; lag_Stressed *1.432338; !(lag.stressed Mean and Var)
[PsDisRatio *0.3961094]; PsDisRatio *0.2019174; !(PsDisRatio Mean and Var)
[NgDisRatio *0.3064143]; NgDisRatio *0.1930179; !(NgDisRatio Mean and Var)
Stressed*0.87; ! residual variance of Stressed
%BETWEEN% ! l)
[Stressed*1.312]; Stressed* 0.046 ; !intercept estimate 1.312 and variance 0.046)
[slope*0.38058]; slope*0.01574; ! NgDisRatio slope (0.38) and variance (0.015)
OUTPUT: TECH9;

**Comment by michaelhallquist** [comment]
Please upload montecarlo.out as a text file so that we can see what the error is in your syntax.

**Comment by mroshanaei** [comment]
Hi, 

Here is the screenshot although I could not saved it as .txt, some wired errors come up.

**Comment by mroshanaei** [comment]
/Users/communitiesProject/Desktop/Screen Shot 2019-10-24 at 3.40.03 PM.png

**Comment by mroshanaei** [comment]
Hi, 

I tried this two methods for saving .out as text, here is the error and I think because there is not any output in .out. right? 

out <- capture.output(summary(montecarlo))
Error in summary.mplusObject(montecarlo) : 
  !is.null(object$results) is not TRUE
> write.table(montecarlo, "mydata.txt")
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0

**Comment by cjvanlissa** [comment]
The .out file is already plain text, so you can just upload that!

**Comment by mroshanaei** [comment]
Hi, Here is the .out file from MPLUS: 

Mplus VERSION 8.3 (Mac)
MUTHEN & MUTHEN
11/02/2019   5:15 PM

INPUT INSTRUCTIONS

  MONTECARLO:
   NAMES ARE Stressed lag_Stressed NgDisRatio PsDisRatio; ! a)


   NOBSERVATIONS = 67200 ; ! b)
   NCSIZES = 1;
   ! let sub represent the range of the number of subjects
   NCSIZE = 1 ;
   CSIZES =  800 (84) ; ! c)
   SEED = 2020 ; ! d)
   NREPS = 100; ! e)
   WITHIN = lag_Stressed NgDisRatio PsDisRatio;! g)
   !BETWEEN = ; ! h)
   !PATMISS = Stressed(0.1) lag_Stressed(0.2) NgDisRatio(0.5) PsDisRatio(.2);
   !PATPROBS = 1; ! f)
   MISSING = Stressed;
  ANALYSIS:
  TYPE = TWOLEVEL RANDOM; ! i)
  !ALGORITHM=INTEGRATION;

  !INTEGRATION = MONTECARLO;
  MODEL POPULATION: ! j)
  %WITHIN% ! k)
  slope | Stressed ON NgDisRatio; ! define the random slope of NgDisRatio main effect
  Stressed ON lag_Stressed*0.54957    ; ! lag.Stressed main effect
  Stressed ON PsDisRatio*-0.18219    ; ! PsDisRatio main effect
  [lag_Stressed *3.131349] ; lag_Stressed *1.432338; !(lag.stressed Mean and Var)
  [PsDisRatio *0.3961094]; PsDisRatio *0.2019174; !(PsDisRatio Mean and Var)
  [NgDisRatio *0.3064143]; NgDisRatio *0.1930179; !(NgDisRatio Mean and Var)
  Stressed*0.87; ! residual variance of Stressed
  %BETWEEN% ! l)
  [Stressed*1.312]; Stressed* 0.046 ; !intercept estimate 1.312 and variance 0.046)
  [slope*0.38058]; slope*0.01574; ! NgDisRatio slope (0.38) and variance (0.015)
  MODEL MISSING:
   [Stressed@-2];
   Stressed ON lag_Stressed*.4 NgDisRatio*.5 PsDisRatio*.5;
  MODEL: ! m)
  %WITHIN% ! k)
  slope | Stressed ON NgDisRatio; ! define the random slope of NgDisRatio main effect
  Stressed ON lag_Stressed*0.54957    ; ! lag.Stressed main effect
  Stressed ON PsDisRatio*-0.18219    ; ! PsDisRatio main effect
  [lag_Stressed *3.131349] ; lag_Stressed *1.432338; !(lag.stressed Mean and Var)
  [PsDisRatio *0.3961094]; PsDisRatio *0.2019174; !(PsDisRatio Mean and Var)
  [NgDisRatio *0.3064143]; NgDisRatio *0.1930179; !(NgDisRatio Mean and Var)
  Stressed*0.87; ! residual variance of Stressed
  %BETWEEN% ! l)
  [Stressed*1.312]; Stressed* 0.046 ; !intercept estimate 1.312 and variance 0.046)
  [slope*0.38058]; slope*0.01574; ! NgDisRatio slope (0.38) and variance (0.015)
  OUTPUT: TECH9;



INPUT READING TERMINATED NORMALLY




SUMMARY OF ANALYSIS

Number of groups                                                 1
Number of observations                                       67200

Number of replications
    Requested                                                  100
    Completed                                                  100
Value of seed                                                 2020

Number of dependent variables                                    1
Number of independent variables                                  3
Number of continuous latent variables                            1

Observed dependent variables

  Continuous
   STRESSED

Observed independent variables
   LAG_STRE    NGDISRAT    PSDISRAT

Continuous latent variables
   SLOPE

Variables with special functions

  Within variables
   LAG_STRE    NGDISRAT    PSDISRAT


Estimator                                                      MLR
Information matrix                                        OBSERVED
Maximum number of iterations                                   100
Convergence criterion                                    0.100D-05
Maximum number of EM iterations                                500
Convergence criteria for the EM algorithm
  Loglikelihood change                                   0.100D-02
  Relative loglikelihood change                          0.100D-05
  Derivative                                             0.100D-03
Minimum variance                                         0.100D-03
Maximum number of steepest descent iterations                   20
Maximum number of iterations for H1                           2000
Convergence criterion for H1                             0.100D-03
Optimization algorithm                                         EMA


SUMMARY OF DATA FOR THE FIRST REPLICATION

     Number of missing data patterns             2
     Cluster information

       Size (s)    Number of clusters of Size s

         84           800

     Average cluster size       84.000

     Estimated Intraclass Correlations for the Y Variables

                Intraclass              Intraclass              Intraclass
     Variable  Correlation   Variable  Correlation   Variable  Correlation

     STRESSED     0.032      LAG_STRE     0.000      NGDISRAT     0.000
     PSDISRAT     0.000


SUMMARY OF MISSING DATA PATTERNS FOR THE FIRST REPLICATION


     MISSING DATA PATTERNS (x = not missing)

           1  2
 STRESSED  x
 LAG_STRE  x  x
 NGDISRAT  x  x
 PSDISRAT  x  x


     MISSING DATA PATTERN FREQUENCIES

    Pattern   Frequency     Pattern   Frequency
          1       39940           2       27260


COVARIANCE COVERAGE OF DATA FOR THE FIRST REPLICATION

Minimum covariance coverage value   0.100


     PROPORTION OF DATA PRESENT


           Covariance Coverage
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       0.594
 LAG_STRE       0.594         1.000
 NGDISRAT       0.594         1.000         1.000
 PSDISRAT       0.594         1.000         1.000         1.000


SAMPLE STATISTICS FOR THE FIRST REPLICATION

NOTE:  The sample statistics for within and between refer to the
       maximum-likelihood estimated within and between covariance
       matrices, respectively.


     ESTIMATED SAMPLE STATISTICS FOR WITHIN


           Means
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
                0.000         3.122         0.306         0.392


           Covariances
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       1.350
 LAG_STRE       0.795         1.430
 NGDISRAT       0.072         0.001         0.191
 PSDISRAT      -0.038         0.000         0.001         0.202


           Correlations
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       1.000
 LAG_STRE       0.572         1.000
 NGDISRAT       0.141         0.002         1.000
 PSDISRAT      -0.073         0.001         0.007         1.000


     ESTIMATED SAMPLE STATISTICS FOR BETWEEN


           Means
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
                3.065         0.000         0.000         0.000


           Covariances
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       0.045
 LAG_STRE       0.000         0.000
 NGDISRAT       0.000         0.000         0.000
 PSDISRAT       0.000         0.000         0.000         0.000


           Correlations
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       1.000
 LAG_STRE       0.000         0.000
 NGDISRAT       0.000         0.000         0.000
 PSDISRAT       0.000         0.000         0.000         0.000


     MAXIMUM LOG-LIKELIHOOD VALUE FOR THE UNRESTRICTED (H1) MODEL IS -243280.028




MODEL FIT INFORMATION

Number of Free Parameters                       13

Loglikelihood

    H0 Value

        Mean                           -243304.863
        Std Dev                            377.620
        Number of successful computations      100

             Proportions                   Percentiles
        Expected    Observed         Expected       Observed
           0.990       0.980      -244183.321    -244268.879
           0.980       0.980      -244080.381    -244260.598
           0.950       0.940      -243926.010    -243957.247
           0.900       0.880      -243788.821    -243848.245
           0.800       0.800      -243622.668    -243653.901
           0.700       0.680      -243502.887    -243523.432
           0.500       0.520      -243304.863    -243290.098
           0.300       0.310      -243106.839    -243100.712
           0.200       0.220      -242987.058    -242958.736
           0.100       0.080      -242820.905    -242847.031
           0.050       0.050      -242683.716    -242757.416
           0.020       0.010      -242529.345    -242619.275
           0.010       0.000      -242426.405    -242599.335

Information Criteria

    Akaike (AIC)

        Mean                            486635.726
        Std Dev                            755.240
        Number of successful computations      100

             Proportions                   Percentiles
        Expected    Observed         Expected       Observed
           0.990       1.000       484878.811     485007.606
           0.980       0.990       485084.689     485224.669
           0.950       0.950       485393.431     485380.061
           0.900       0.920       485667.810     485682.984
           0.800       0.780       486000.116     485931.983
           0.700       0.690       486239.678     486133.283
           0.500       0.480       486635.726     486597.241
           0.300       0.320       487031.774     487065.734
           0.200       0.200       487271.336     487269.352
           0.100       0.120       487603.642     487621.614
           0.050       0.060       487878.021     487930.067
           0.020       0.020       488186.763     488133.873
           0.010       0.020       488392.641     488547.196

    Bayesian (BIC)

        Mean                            486754.227
        Std Dev                            755.240
        Number of successful computations      100

             Proportions                   Percentiles
        Expected    Observed         Expected       Observed
           0.990       1.000       484997.311     485126.107
           0.980       0.990       485203.190     485343.170
           0.950       0.950       485511.932     485498.561
           0.900       0.920       485786.311     485801.484
           0.800       0.780       486118.616     486050.484
           0.700       0.690       486358.179     486251.783
           0.500       0.480       486754.227     486715.742
           0.300       0.320       487150.274     487184.235
           0.200       0.200       487389.837     487387.852
           0.100       0.120       487722.142     487740.115
           0.050       0.060       487996.521     488048.567
           0.020       0.020       488305.263     488252.373
           0.010       0.020       488511.142     488665.697

    Sample-Size Adjusted BIC (n* = (n + 2) / 24)

        Mean                            486712.912
        Std Dev                            755.240
        Number of successful computations      100

             Proportions                   Percentiles
        Expected    Observed         Expected       Observed
           0.990       1.000       484955.997     485084.793
           0.980       0.990       485161.875     485301.856
           0.950       0.950       485470.618     485457.247
           0.900       0.920       485744.996     485760.170
           0.800       0.780       486077.302     486009.170
           0.700       0.690       486316.864     486210.469
           0.500       0.480       486712.912     486674.427
           0.300       0.320       487108.960     487142.921
           0.200       0.200       487348.522     487346.538
           0.100       0.120       487680.828     487698.800
           0.050       0.060       487955.207     488007.253
           0.020       0.020       488263.949     488211.059
           0.010       0.020       488469.827     488624.383



MODEL RESULTS

                              ESTIMATES              S. E.     M. S. E.  95%  % Sig
                 Population   Average   Std. Dev.   Average             Cover Coeff
Within Level

 STRESSED   ON
  LAG_STRESS          0.550     0.5494     0.0042     0.0040     0.0000 0.950 1.000
  PSDISRATIO         -0.182    -0.1820     0.0107     0.0106     0.0001 0.920 1.000

 Means
  LAG_STRESS          3.131     3.1315     0.0048     0.0046     0.0000 0.910 1.000
  NGDISRATIO          0.306     0.3063     0.0016     0.0017     0.0000 0.960 1.000
  PSDISRATIO          0.396     0.3963     0.0017     0.0017     0.0000 0.980 1.000

 Variances
  LAG_STRESS          1.432     1.4332     0.0092     0.0078     0.0001 0.890 1.000
  NGDISRATIO          0.193     0.1930     0.0010     0.0011     0.0000 0.960 1.000
  PSDISRATIO          0.202     0.2018     0.0011     0.0011     0.0000 0.930 1.000

 Residual Variances
  STRESSED            0.870     0.8701     0.0060     0.0063     0.0000 0.940 1.000

Between Level

 Means
  STRESSED            1.312     1.3124     0.0152     0.0157     0.0002 0.950 1.000
  SLOPE               0.381     0.3817     0.0114     0.0117     0.0001 0.960 1.000

 Variances
  STRESSED            0.046     0.0462     0.0034     0.0033     0.0000 0.940 1.000
  SLOPE               0.016     0.0163     0.0047     0.0050     0.0000 0.950 0.930


QUALITY OF NUMERICAL RESULTS

     Average Condition Number for the Information Matrix      0.353E-02
       (ratio of smallest to largest eigenvalue)


TECHNICAL 1 OUTPUT


     PARAMETER SPECIFICATION FOR WITHIN


           NU
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
                    0             0             0             0


           LAMBDA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED           0             0             0             0
 LAG_STRE           0             0             0             0
 NGDISRAT           0             0             0             0
 PSDISRAT           0             0             0             0


           THETA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED           0
 LAG_STRE           0             0
 NGDISRAT           0             0             0
 PSDISRAT           0             0             0             0


           ALPHA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
                    0             1             2             3


           BETA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED           0             4             0             5
 LAG_STRE           0             0             0             0
 NGDISRAT           0             0             0             0
 PSDISRAT           0             0             0             0


           PSI
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED           6
 LAG_STRE           0             7
 NGDISRAT           0             0             8
 PSDISRAT           0             0             0             9


     PARAMETER SPECIFICATION FOR BETWEEN


           NU
              STRESSED
              ________
                    0


           LAMBDA
              SLOPE         STRESSED
              ________      ________
 STRESSED           0             0


           THETA
              STRESSED
              ________
 STRESSED           0


           ALPHA
              SLOPE         STRESSED
              ________      ________
                   10            11


           BETA
              SLOPE         STRESSED
              ________      ________
 SLOPE              0             0
 STRESSED           0             0


           PSI
              SLOPE         STRESSED
              ________      ________
 SLOPE             12
 STRESSED           0            13


     STARTING VALUES FOR WITHIN


           NU
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
                0.000         0.000         0.000         0.000


           LAMBDA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       1.000         0.000         0.000         0.000
 LAG_STRE       0.000         1.000         0.000         0.000
 NGDISRAT       0.000         0.000         1.000         0.000
 PSDISRAT       0.000         0.000         0.000         1.000


           THETA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       0.000
 LAG_STRE       0.000         0.000
 NGDISRAT       0.000         0.000         0.000
 PSDISRAT       0.000         0.000         0.000         0.000


           ALPHA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
                0.000         3.131         0.306         0.396


           BETA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       0.000         0.550         0.000        -0.182
 LAG_STRE       0.000         0.000         0.000         0.000
 NGDISRAT       0.000         0.000         0.000         0.000
 PSDISRAT       0.000         0.000         0.000         0.000


           PSI
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       0.870
 LAG_STRE       0.000         1.432
 NGDISRAT       0.000         0.000         0.193
 PSDISRAT       0.000         0.000         0.000         0.202


     STARTING VALUES FOR BETWEEN


           NU
              STRESSED
              ________
                0.000


           LAMBDA
              SLOPE         STRESSED
              ________      ________
 STRESSED       0.000         1.000


           THETA
              STRESSED
              ________
 STRESSED       0.000


           ALPHA
              SLOPE         STRESSED
              ________      ________
                0.381         1.312


           BETA
              SLOPE         STRESSED
              ________      ________
 SLOPE          0.000         0.000
 STRESSED       0.000         0.000


           PSI
              SLOPE         STRESSED
              ________      ________
 SLOPE          0.016
 STRESSED       0.000         0.046


     POPULATION VALUES FOR WITHIN


           NU
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
                0.000         0.000         0.000         0.000


           LAMBDA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       1.000         0.000         0.000         0.000
 LAG_STRE       0.000         1.000         0.000         0.000
 NGDISRAT       0.000         0.000         1.000         0.000
 PSDISRAT       0.000         0.000         0.000         1.000


           THETA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       0.000
 LAG_STRE       0.000         0.000
 NGDISRAT       0.000         0.000         0.000
 PSDISRAT       0.000         0.000         0.000         0.000


           ALPHA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
                0.000         3.131         0.306         0.396


           BETA
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       0.000         0.550         0.000        -0.182
 LAG_STRE       0.000         0.000         0.000         0.000
 NGDISRAT       0.000         0.000         0.000         0.000
 PSDISRAT       0.000         0.000         0.000         0.000


           PSI
              STRESSED      LAG_STRE      NGDISRAT      PSDISRAT
              ________      ________      ________      ________
 STRESSED       0.870
 LAG_STRE       0.000         1.432
 NGDISRAT       0.000         0.000         0.193
 PSDISRAT       0.000         0.000         0.000         0.202


     POPULATION VALUES FOR BETWEEN


           NU
              STRESSED
              ________
                0.000


           LAMBDA
              SLOPE         STRESSED
              ________      ________
 STRESSED       0.000         1.000


           THETA
              STRESSED
              ________
 STRESSED       0.000


           ALPHA
              SLOPE         STRESSED
              ________      ________
                0.381         1.312


           BETA
              SLOPE         STRESSED
              ________      ________
 SLOPE          0.000         0.000
 STRESSED       0.000         0.000


           PSI
              SLOPE         STRESSED
              ________      ________
 SLOPE          0.016
 STRESSED       0.000         0.046


TECHNICAL 9 OUTPUT

  Error messages for each replication (if any)



     Beginning Time:  17:15:20
        Ending Time:  17:16:25
       Elapsed Time:  00:01:05



MUTHEN & MUTHEN
3463 Stoner Ave.
Los Angeles, CA  90066

Tel: (310) 391-9971
Fax: (310) 391-8971
Web: www.StatModel.com
Support: Support@StatModel.com

Copyright (c) 1998-2019 Muthen & Muthen

**Comment by michaelhallquist** [comment]
Hi there, Mahnaz,

I didn't have any problem running your code... Attached is the script for running your simulation within mplusModeler. Look in fitMonteCarlo$results. Also, you'll need to change the Mplus_command on your machine to point to where it lives on your computer (or, if it's in the default location, you can just delete that argument).

Hope this helps,
Michael

[working_input.R.txt](https://github.com/michaelhallquist/MplusAutomation/files/3872812/working_input.R.txt)

**Comment by mroshanaei** [comment]
Hi

Thanks for your reply. The problem is its not running on R and the result
is empty. Can u please try it on R? I know It is running on MPlus.

Thanks,
Mahnaz

**Comment by michaelhallquist** [comment]
Hi Mahnaz,

Please see the working_input.R file attached to my previous message. It is the R script I ran that worked just fine.

Michael
