### ISSUE TITLE
length of conditions (e.g., the condition has length > 1 and only the first element will be used)

### ISSUE THREAD

**Issue by hplieninger** [michaelhallquist/MplusAutomation#114]
## Background

I learned from Henrik Bengtsson to be cautions with the length of condtions:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">All <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> folks, pls run R with:<br><br>_R_CHECK_LENGTH_1_CONDITION_=verbose<br>_R_CHECK_LENGTH_1_LOGIC2_=verbose<br><br>set. I keep finding bugs in CRAN &amp; <a href="https://twitter.com/Bioconductor?ref_src=twsrc%5Etfw">@Bioconductor</a> pkgs this way and some of them are serious =&gt; wrong scientific results. Report to maintainer when you spot these <a href="https://t.co/Llarww3Xc6">https://t.co/Llarww3Xc6</a></p>&mdash; Henrik Bengtsson (@henrikbengtsson) <a href="https://twitter.com/henrikbengtsson/status/1188197161780989953?ref_src=twsrc%5Etfw">October 26, 2019</a></blockquote>

See also: https://twitter.com/henrikbengtsson/status/1144755659965026305?s=20 and https://cran.r-project.org/doc/manuals/r-devel/R-ints.html#Tools

## Examples

Setting these environment variables to true or verbose raises several issues in MplusAutomation, because often conditions such as the following are used: 

``` r
if (!is.na(1:2) & TRUE) {
    # code  
}

if (!is.null(1) && is.na(1:2)) {
    # code
}
```

Here are two examples:
https://github.com/michaelhallquist/MplusAutomation/blob/71974f5e8eea64e6a088b2bd5e95bc64b091d446/R/readModels.R#L166

https://github.com/michaelhallquist/MplusAutomation/blob/71974f5e8eea64e6a088b2bd5e95bc64b091d446/R/readModels.R#L239

## Issue
I don't have encountered any serious errors because of that. However, I would appreciate if this could be addressed, because that would allow me to set these environment variables to "verbose" without the "unproblematic" issues raised by situations such as those described above.

I think one way to address this is to replace `is.na(x)` in such conditions with `isTRUE(is.na(x))`.

**Comment by JWiley** [comment]
@hplieninger will you check if the commit f57977b addresses this? Would also appreciate testing as much as you can on the latest commit as its a bit hard to know if the less strict conditionals we used before will break (e.g., if(isTRUE(length(1))) is FALSE will not work although if(length(1)) will be evaluated).
