### ISSUE TITLE
Specific indirect effects not obtained with Mplus 8.4

### ISSUE THREAD

**Issue by sda030** [michaelhallquist/MplusAutomation#117]
I would expect that 
`out<- MplusAutomation::readModels(what = "indirect", target = "example.with.indirect.effects.out")` provided the $specific, as found in the out-file, yet nothing in the object. Issue seems to arise in the `getMultilineSection` function because the output from this for $specific is empty.

Attached example file is admittedly not a small reproducible situation, but all I had at hand.
[example with indirect effects.txt](https://github.com/michaelhallquist/MplusAutomation/files/4063493/example.with.indirect.effects.txt)

P.S. I never get time to sit down to grasp the magic in the MplusAutomation engines, but will prioritize it when I get time so I can contribute more.

**Comment by michaelhallquist** [comment]
This has now been fixed in the development version of the package. The issue was that Mplus 8.4 added Specific indirect 1, Specific indirect 2, etc. as subsection headers, which was not the old format. I've now implemented a branch in the parser logic to support either format.
