### ISSUE TITLE
Error extracting invarinace testing in output file

### ISSUE THREAD

**Issue by sda030** [michaelhallquist/MplusAutomation#120]
I receive this error message for all my files with invariance testing: `Error extracting invarinace testing in output file: 2pl_dif_tiltak_auto.out`
<simpleError in apply(test_rows[, -1], 2, as.numeric): dim(X) must have a positive length>

[2pl_dif_tiltak_auto.txt](https://github.com/michaelhallquist/MplusAutomation/files/4338773/2pl_dif_tiltak_auto.txt)

**Comment by michaelhallquist** [comment]
There was a small bug in the way the invariance extraction was working for just 2 variants (here, scalar and configural). I've fixed the problem and verified that your output now parses using the development version of the package.

**Comment by sda030** [comment]
Neat!
