### ISSUE TITLE
Flexible traceplots with export to pdf

### ISSUE THREAD

**Issue by MaksimRudnev** [michaelhallquist/MplusAutomation#124]
MplusAutomation::mplus.traceplot is great, but it's limited to dislaying traceplots and doesn't deal with autocorrelations. I suggest adding a more flexible function that exports all or some traceplots and autocorrelation plots to pdf. It makes it easy to report these traceplots which is a recommended practice. In addition, it computes PSR for every parameter, which is not available in Mplus itself. 
Please consider the code:
https://github.com/MaksimRudnev/LittleHelpers/blob/master/R/MplusHelpers.R

#enhancement

**Comment by cjvanlissa** [comment]
@MaksimRudnev in the meanwhile, also consider the R-package `tidySEM`, which I wrote to do this with my own analyses. tidySEM has some advantages over existing SEM graphing packages, including recursive handling of multilevel and multigroup models, being able to customize every plot element by simply changing values in a data.frame, and outputting a ggplot object that can be further processed and saved as any other old ggplot.

**Comment by cjvanlissa** [comment]
Sorry, I misread this comment.

**Comment by cjvanlissa** [comment]
It should be possible to just write an adapter for `shinystan`
