### ISSUE TITLE
runModels not working with github version

### ISSUE THREAD

**Issue by kyletcox** [michaelhallquist/MplusAutomation#126]
I'm running a simulation and need to extract the psr from the tech8 mplus output. This is not possible with the cran version of MplusAutomation but I saw that the more recent version on here has that capability. I have run the simulation using the cran version of MplusAutomation  several times (all successful) but I cannot get the runModels() function to work using the github version. I'm only running a single .inp file and have tried the filename and full path but get the following error

>     runModels("C:/Simulations/croon_single_level_latent_interaction_3way/true_model.mplus.inp")
Error in paste("Target directory: ", directory, sep = "") : 
  object 'directory' not found

>     runModels("true_model.mplus.inp")
Error in paste("Target directory: ", directory, sep = "") : 
  object 'directory' not found

Again, these run perfectly with the cran version. If it matters I also get this error (or similar) with the getwd() function right after running the code above:
> getwd()
[1] "C:/Simulations/croon_single_level_latent_interaction_3way"
Warning messages:
1: In list(...) : closing unused connection 5 (Mplus Run Models.log)
2: In list(...) : closing unused connection 4 (Mplus Run Models.log)

Session info below if helpful:
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
LC_TIME=English_United States.1252    

attached base packages:
stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
MplusAutomation_0.7-3 devtools_2.3.1        usethis_1.6.1        

loaded via a namespace (and not attached):
Rcpp_1.0.5        plyr_1.8.6        pillar_1.4.6      compiler_4.0.2    prettyunits_1.1.1 remotes_2.2.0     tools_4.0.2       boot_1.3-25       testthat_2.3.2   
digest_0.6.25     pkgbuild_1.1.0    pkgload_1.1.0     tibble_3.0.3      memoise_1.1.0     lifecycle_0.2.0   gtable_0.3.0      lattice_0.20-41   texreg_1.37.5    
pkgconfig_2.0.3   rlang_0.4.7       cli_2.0.2         rstudioapi_0.11   parallel_4.0.2    curl_4.3          proto_1.0.0       coda_0.19-3       httr_1.4.2       
dplyr_0.8.5       withr_2.2.0       vctrs_0.3.2       desc_1.2.0        fs_1.4.1          tidyselect_1.1.0  rprojroot_1.3-2   grid_4.0.2        data.table_1.13.0
glue_1.4.1        R6_2.4.1          processx_3.4.3    fansi_0.4.1       gsubfn_0.7        sessioninfo_1.1.1 pander_0.6.3      purrr_0.3.4       callr_3.4.3      
ggplot2_3.3.2     magrittr_1.5      backports_1.1.9   scales_1.1.1      ps_1.3.4          ellipsis_0.3.1    assertthat_0.2.1  xtable_1.8-4      colorspace_1.4-1

**Comment by michaelhallquist** [comment]
Sorry about that. There was an fix that I made several weeks ago that I had forgotten to push. The updated version should work.

-Michael

**Comment by kyletcox** [comment]
Got back to this and implemented everything. Works perfectly!
Thanks,
Kyle
________________________________
