### ISSUE TITLE
Is it possible to change default "MISSING = .;" to another value?

### ISSUE THREAD

**Issue by atanasj** [michaelhallquist/MplusAutomation#128]
When using the `mplusObject` function, it automatically inserts `MISSING=.;` in the resultant `.inp` files. However, when I included an alternative value for the missing data e.g., `MISSING ARE ALL (-999);`, it includes both lines of syntax in the resultant `.inp` file.

Is it possible to set the values of missing variables or do missing values need to be changed to match the default behaviour of this function?

**Comment by cjvanlissa** [comment]
I believe that it automatically codes missing values when writing the data file. You should code missing values as NA in R when you read the original data.

**Comment by atanasj** [comment]
Thanks @cjvanlissa, that makes it much more useful. So leave as `NA` and all is well! I think reading the `inp` files, it seems to replace `NA` with `.`.  I'm happy to close!
