### ISSUE TITLE
detectColumnNames function is not identifying the right column names in Model Results section

### ISSUE THREAD

**Issue by wbelzak** [michaelhallquist/MplusAutomation#129]
Hi Michael,

Thanks for creating this package. It's great! I'm having an issue, however. Namely, I'm trying to extract model parameters from 'readModels', but I cannot seem to get the standard errors and p-values from the Mplus Model Results section. Instead, I only get the parameter names and point estimates.

I have traced this problem back to the 'detectColumnNames' function, which reads the 'modelSection' input (i.e., Model Results section from Mplus) and identifies the column names. However, the Mplus output file that I'm using has a Model Results section that includes a leading white space on the first row. This adversely affects what the 'thisLine' and 'nextLine' objects are, and subsequently what column names are applied to the Model Results section in Mplus. It only detects the parameter name and point estimate columns, and not the standard error or p-value columns.

I included this code on line 745 (first bit of code after the while statement) and it seems to be working for me now:
   
    #if line has no text, move line to row with first text.
    if(modelSection[line] == "") line <- which(!(modelSection == ""))[1]
    
I'm happy to share my Mplus output file if you cannot replicate this issue. FYI, I'm using Mplus 8.4.

Thanks,
Will Belzak

**Comment by cjvanlissa** [comment]
If we don't need the line breaks to distinguish separate chunks, it would be better to drop all at once, as conditionals are slow:

`modelSection <- modelSection[!modelSection == ""]`

**Comment by michaelhallquist** [comment]
Hi Will, thanks for this information. I have not had this experience with readModels across a few hundred outputs that get run as part of the package tests I conduct periodically. Could you upload your .out file here? You'll have to change it to .txt for Github to allow it, but that's fine (I can change it back on my end).

Thanks,
Michael

**Comment by wbelzak** [comment]
Hi Michael and C.J.,

After updating R to version 4.0.3 (from 3.6.3), the issue has been resolved. I'm not sure how, but MplusAutomation seems to be working as intended now.

Best,
Will

**Comment by michaelhallquist** [comment]
Sweet, glad to hear it, Will. It's possible that the issue resolved with the recent release of v0.8 of the package to CRAN, which you may have gotten en passant with the R upgrade. I'll close this for now, but feel free to reopen if the error recurs.

Best,
Michael
