### ISSUE TITLE
Bug in v0.8?

### ISSUE THREAD

**Issue by cbratt** [michaelhallquist/MplusAutomation#130]
I believe there might be a bug in MplusAutomation's use of the update() function, introduced in v0.8.

Define a linear regression model for Mplus, using MplusAutomation and built-in data in R, then run the model.

```
library(MplusAutomation)
test_model <- mplusObject(VARIABLE = "usevariables = mpg cyl;",
                   MODEL = "mpg ON cyl;",
                   rdata = mtcars)

mplusModeler(test_model,
             hashfilename = F,
             modelout = "test_model.inp",
             dataout = "mplusdata.dat",
             run =   1L
)
unlink("test_model.inp")
```

No problem so far.

Now define the same model as above, but leave out the data. Then add the data using update(), and try to run the model.

```
test_model2 <- mplusObject(VARIABLE = "usevariables = mpg cyl;",
                   MODEL = "mpg ON cyl;"
                   )

test_model3 <- update(test_model2,
                          rdata = mtcars)

mplusModeler(test_model3,
             hashfilename = F,
             modelout = "test_model3.inp",
             dataout = "mplusdata.dat",
             run =   1L
)
```

The last command results in the following error message:

```
When hashfilename = FALSE, writeData cannot be 'ifmissing', setting to 'always'
Wrote model to: test_model3.inp
Wrote data to: mplusdata.dat
Error in .cleanHashData(df = df, keepCols = keepCols, imputed = imputed) : 
  missing(keepCols) || is.character(keepCols) || is.numeric(keepCols) ||  .... is not TRUE
```

Best,
Christopher Bratt

**Comment by michaelhallquist** [comment]
Thanks for these details, Chris. @JWiley , would you be able to look at this as time permits?

**Comment by JWiley** [comment]
Thanks, I think it was never built to not have an R dataset in the original object.
Should be fairly easy to fix, thanks for the report.

**Comment by cbratt** [comment]
Works like a charm in previous versions. And sometimes I even need to wait with providing the data so update() will update added variables correctly. 

Thanks for the effort!
