### ISSUE TITLE
Question about the console output generated by runModels

### ISSUE THREAD

**Issue by cjvanlissa** [michaelhallquist/MplusAutomation#131]
@michaelhallquist @JWiley , I notice that, when runModels is called indirectly (for example, through unit tests in testthat, or in code chunks in Rmarkdown), all of the console output generated by `system()` is shown in the R-console. This takes a TREMENDOUS amount of time: the runtime of my testthat folder for `tidyLPA` went down from 3 hours to 2 minutes after I implemented some hacks that prevent this output from being shown. So my question is: What is the intended behavior? From the call to `system()`, I can tell that you flexibly allow users to print output to console. But to be able to suppress the output of system would require to set the argument `intern = TRUE`, and users cannot currently do this.

I'm happy to send a pull request to sort this out, but first it's useful to know if you've given this any thought, and what the intended behavior of runModels() should be.

**Comment by michaelhallquist** [comment]
Thanks, Caspar! Looks good to me -- merged your PR.

Michael
