### ISSUE TITLE
extract EFA function not showing in version 0.8

### ISSUE THREAD

**Issue by NatashaMae2018** [michaelhallquist/MplusAutomation#133]
Hi,

I'm relatively new to rStudio, but I downloaded the MPlus Automation packaged for my current project. I'm doing a number of EFAs and have gone to use the "extractEFAparameters" function but it does not appear to show up in my little menu when I type "extract and when I try to run it, I'm told "could not find function "extractEFAparameters". Is there something that I am missing?

Thanks,
Natasha

**Comment by michaelhallquist** [comment]
Hi Natasha,

All of the EFA parameters are provided through readModels in the $parameters element. The extractEFAparameters function is just used internally by the package to do the work, then readModels packages these into the larger mplus.model object.

Michael
