### ISSUE TITLE
Bug in runModels referring to filefilter?

### ISSUE THREAD

**Issue by oliverbuss** [michaelhallquist/MplusAutomation#134]
With reference to this [post](https://groups.google.com/g/mplusautomation/c/GyK-XzCiV58) in the MplusAutomation google group, I think there might be a bug referring to line 296 of runModels:
 `   if (!is.null(filefilter)) { filelist <- grep(filefilter, filefilter, perl=TRUE, value=TRUE) } `

I assume that the first two arguments here should be: 
`grep(pattern = filefilter, x = filelist, perl=TRUE, value=TRUE) } `

**Comment by michaelhallquist** [comment]
Thanks, Oliver. You're precisely right -- I mistyped the second argument there when I refactored the function! I just fixed it on the Github version (b389e544aa6f605d79f9567ce33f981c9289f6e0) and notified the author of that post.
