### ISSUE TITLE
Feature Request: quiet=TRUE

### ISSUE THREAD

**Issue by sda030** [michaelhallquist/MplusAutomation#136]
Very simple request for those kind of analyses with many many runs. This output quickly fills up the console:
Running model: simple_xrekar_f_7.inp 
System command: C:\WINDOWS\system32\cmd.exe /c cd "C:\Users\py128\NIFU\20750 Evalueringen av Tett på realfag - General\Spørreundersøkelser\Analyser\mplus" && "Mplus" "simple_xrekar_f_7.inp" 
Reading model:  simple_xrekar_f_7.out 
Wrote model to: simple_xrekar_e_01.inp
Wrote data to: simple_xrekar_e_01.dat
Often this is useless information. If things go awry, then either it is an error/warning that is useful, or one can turn `quiet=FALSE`
Preferably in mplusModeler()

**Comment by cjvanlissa** [comment]
Agree. @michaelhallquist , to make sure this also works on windows, the code in my pull request #132 is useful.

**Comment by cjvanlissa** [comment]
This can be closed
