### ISSUE TITLE
Problem at reading BPARAMETERS when FSCORES are also computed.

### ISSUE THREAD

**Issue by secastroal** [michaelhallquist/MplusAutomation#138]
Hi, 

I am running some multilevel factor models using the Bayesian estimation in Mplus. In my input file, I am requesting to save the samples from the MCMC algorithm as well as the estimated factor scores of the latent variables in my model.

This is the code in the input file:
SAVEDATA: BPARAMETERS = samples.dat;
          FILE is fscores.dat;
          SAVE = FSCORES (100 10);

The problem I am running into is that readModels() can not properly read the saved file of the MCMC samples when I also save the factor scores.

To solve this, I have to open samples.dat and delete the last 100 samples (in my case), which correspond to the samples used to estimate the factor scores.

Although this is happening to me with multilevel Bayesian factor models, my guess is that this will happen with any kind of factor model estimated via Bayesian methods as soon as the MCMC samples, as well as the factor scores, are saved.

If you find it useful, I can share the output files of one of my analyses.

**Comment by michaelhallquist** [comment]
Sorry it took so long to get to this, but I recently implemented a fix for this problem, which you see/obtain from this commit: a6d7138.

Best,
Michael
