### ISSUE TITLE
Extracting loadings in EFA

### ISSUE THREAD

**Issue by desphua** [michaelhallquist/MplusAutomation#139]
I understand that v0.8 allows for extracting parameters from EFA models. But I can't seem to successfully extract the factor loadings.
Can I know what's the correct command?
I tried: paramExtract(efa_models$parameters$efa$f2, "loading") but it gives error "Error in x[, "paramHeader"] : incorrect number of dimensions"

**Comment by michaelhallquist** [comment]
I don't know if paramExtract has been developed for efa models. But if you have a simple setup like this, you'll see it:

```
m <- readModels("efa_model.out")
m$parameters
```
