### ISSUE TITLE
MplusAutomation does not work with the demo version of Mplus out of the box

### ISSUE THREAD

**Issue by albertostefanelli** [michaelhallquist/MplusAutomation#140]
Hi,

thanks for the fantastic package. I am using MplusAutomation to teach but I am using the free demo version of Mplus 
Unfortunately MplusAutomation does not work out of the box with the demo version. 
The problem is that both the folder and the executable are called differently for the demo version 
The folder is called "Mplus Demo" while the executable is called MpDemo.
Renaming both the folder and the executable fixes the problem. 
This can be also achieved by specifying a new path in Mplus_command of mplusModeler

I opened the issue mostly for documentation purposes.

**Comment by JWiley** [comment]
@albertostefanelli could you test the latest development version of MplusAutomation?

```
devtools::install_github("MichaelHallquist/MplusAutomation")
```

I've tried to build in code that tries harder to find a valid Mplus command and if cannot find a full mplus, tries to find an Mplus Demo. This is tricky, however, as they differ across versions and operating systems. A few tests from my end seem to be working, but it would help to get more people on more systems testing and reporting.

**Comment by michaelhallquist** [comment]
Given that this issue hasn't been updated in quite a while and @JWiley made changes that likely address the problem, I will close this as resolved. Please feel free to reopen it if you encounter problems using the Mplus Demo with the package.
