### ISSUE TITLE
extractIndirect function not showing up 

### ISSUE THREAD

**Issue by AnnieBFox** [michaelhallquist/MplusAutomation#141]
I'm using MplusAutomation to run mediation models.  When I go to use the "extractIndirect" function, I get an error message that the function does not exist.  I can locate the function via help (?extractIndirect), but it does not show up in the help table of contents when I click on the package. In RStudio, the function does not show up as an auto-fill possibility when I start typing "extract".  I've tried reinstalling the package, installing the development version, and two different versions of Mplus (8.4 and 8.6).  I've encountered the same problem on two different machines.  Any ideas why the function isn't showing up?

**Comment by JWiley** [comment]
Hi Annie,

I'm not sure there is an extractIndirect function. MplusAutomation does
extract the indirect estimates using readModels and they show up in the
results, is that what you are after?

Cheers,

Josh

**Comment by michaelhallquist** [comment]
I'm closing this issue for now. There was never an extractIndirect function available to users. But in v1.0, @cjvanlissa added a number of helper functions, including `get_indirect` that extract specific sections from the objects returned by readModels. So, you can use this kind of approach moving forward:

```
obj <- readModels("test.out")
get_indirect(obj)
```

Hope this helps,
Michael
