### ISSUE TITLE
Error when reading models: "no non-missing arguments to max; returning -InfError"

### ISSUE THREAD

**Issue by dinanajiarch** [michaelhallquist/MplusAutomation#144]
When attempting to read in the output using `readModels` or when using `mplusModeler` to run the model, I get this error below. And it seems like it started happening after the new Mplus update (8.6). I have tried running the model in both R and directly in Mplus and then reading it in using `readModels`, and no luck. I have tried running past projects with unchanged code and still getting this error below. 

For example, if I am trying to run the model in R, this is the error I will get:

`m.step1.fit <- mplusModeler(m.step1, 
                            dataout=here("three_step","Step1.dat"),
                            modelout=here("three_step","Step1.inp"),
                            check=TRUE, run = TRUE, hashfilename = FALSE)`
```
Error extracting MODEL RESULTS in output file: C:/Desktop/mystudy.out
<simpleError in startLine:endLine: NA/NaN argument>
Warning message:
In max(hlines) : no non-missing arguments to max; returning -Inf
```

If I am reading in the model (and whether the model was run in R or Mplus):
`model_name <- readModels(here("three_step", "Step1.out"), quiet = TRUE)`
```
no non-missing arguments to max; returning -InfError extracting MODEL RESULTS in output file: C:/Desktop/mystudy.out
<simpleError in startLine:endLine: NA/NaN argument>
```

The `readModels` function still works, however, the parameter values are missing from the object. These values are needed to extract probabilities from the latent class model. I am not sure how to proceed from here. I hope I provided enough information. Thank you.

**Comment by michaelhallquist** [comment]
Thanks for this report. I believe this problem stems from Mplus 8.6 adding new top-level section headers to the outputs in some mixture models. This throws off the parsing of sections, which is fundamental to the package working. I have added code to identify the new sections (at least the ones I saw). If you install the development version of the package from Github, this should now work. Without seeing your .out file, I cannot be certain of the fix. If you're still having problems, feel free to reopen the issue.

**Comment by dinanajiarch** [comment]
Thanks so much!
