### ISSUE TITLE
Read and extract unaligned output

### ISSUE THREAD

**Issue by fangxiaobaozi** [michaelhallquist/MplusAutomation#168]
Hi Michael!

I have messy text in the middle of the output like the figure below (don't know how this happens). 
<img width="622" alt="Screenshot 2022-05-01 at 11 55 58 PM" src="https://user-images.githubusercontent.com/23390965/166182407-05b845ff-1058-48ca-99d2-a6a0515fa5e8.png">

When extracting parameters, the `ReadModels` function "could not find end of the input". Do you have any ideas on how to extract the parameters below those text? I also attached the output file below.

Thanks!!

--
Yuan Fang
Lab for Developmental and Health Research Methodology
Department of Psychology
University of Notre Dame
Email: yfang6@nd.edu

[rep-1.txt](https://github.com/michaelhallquist/MplusAutomation/files/8600721/rep-1.txt)

**Comment by michaelhallquist** [comment]
Hi Yuan Fang,

Unfortunately, that looks like a bug in Mplus that would be hard to code around. I would encourage you to share it with the StatModel folks. To extract those parameters, I would suggest deleting those misplaced lines (in a text editor) and then try readModels again. I realize that only works if you have a few outputs, but that's the only thing I can think of.

Best,
Michael

**Comment by fangxiaobaozi** [comment]
No problem Michael! I have thousands of output files but luckily I have found where the bug was and was able to eliminate the problem. Still thanks for your reply and for this useful package you have developed. It helped a lot in my simulation studies!


Best,
Yuan


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "michaelhallquist/MplusAutomation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 凌晨1:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [michaelhallquist/MplusAutomation] Read and extract unaligned output (Issue #168)





 
Hi Yuan Fang,
 
Unfortunately, that looks like a bug in Mplus that would be hard to code around. I would encourage you to share it with the StatModel folks. To extract those parameters, I would suggest deleting those misplaced lines (in a text editor) and then try readModels again. I realize that only works if you have a few outputs, but that's the only thing I can think of.
 
Best,
 Michael
