### ISSUE TITLE
warning message on is.na(columnNames) || is.null(columnNames)

### ISSUE THREAD

**Issue by beib** [michaelhallquist/MplusAutomation#171]
Following warning message is shown despite models running fine.

`Warning message:
In is.na(columnNames) || is.null(columnNames) :
  'length(x) = 7 > 1' in coercion to 'logical(1)'`

**Comment by sda030** [comment]
Issue arises in extracting modindices. No modindices element in the output. (I believed it was always present before?)
``` r
library(lavaan)
library(MplusAutomation)
tmp <- lavaan::simulateData(model = "f =~ x1 + 1.2*x2 + .8*x3 + .9*x4 + 1.1*x5")
x <- mplusObject(rdata = tmp, MODEL = "f by x1-x5;", OUTPUT = "MOD(ALL);")
x <- mplusModeler(x, modelout = "tmp.inp", run = 1L)
#> Warning in is.na(columnNames) || is.null(columnNames): 'length(x) = 7 > 1' in
#> coercion to 'logical(1)'
```

<sup>Created on 2022-07-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by haozhou1988** [comment]
probably because of the highlighted part of extractModIndices_1 function. See the attachment
![1663221027872](https://user-images.githubusercontent.com/5347702/190325130-c7f7ffbd-2f04-44cf-8c32-769e5784095f.png)
