### ISSUE TITLE
Tech10 extraction

### ISSUE THREAD

**Issue by cateh** [michaelhallquist/MplusAutomation#173]
Hi - I recently updated to MPLUS 8.8 and since then get an error on running mplusautomation if I request TECH10: 
<simpleError in bivarFitData[mPos, ] <- c(vars, values): number of items to replace is not a multiple of replacement length>

I'm wondering if the 8.8 version has some changes to the bivariate model fit output causing this error?

**Comment by sda030** [comment]
Not really the same issue, but while we are at it, the package does not really capture this tech10 message, as it only returns an empty list instead:
     TECH10 OUTPUT FOR THE CATEGORICAL VARIABLES IS NOT AVAILABLE BECAUSE THE FREQUENCY
     TABLE FOR THE LATENT CLASS INDICATOR MODEL PART IS TOO LARGE.
Is this a design choice? Would it be better to be more explicit about capturing it, e.g. returning NA? An empty list makes me check the output file manually, in fear of it being missed.
[example.txt](https://github.com/michaelhallquist/MplusAutomation/files/9240682/example.txt)

**Comment by rebekabalogh** [comment]
Hi, just wondering if there is any update on this? I'm still having issues extracting tech10 results with the package. Thanks very much!

**Comment by sam-crawley** [comment]
I've created a PR to fix this.

**Comment by michaelhallquist** [comment]
Fixed by #182
