### ISSUE TITLE
Fatal error not captured

### ISSUE THREAD

**Issue by sda030** [michaelhallquist/MplusAutomation#175]
Not capturing this error:
*** FATAL ERROR
     THERE IS NOT ENOUGH MEMORY SPACE TO RUN Mplus ON THE CURRENT
     INPUT FILE.  THE ANALYSIS REQUIRES 5 DIMENSIONS OF INTEGRATION RESULTING
     IN A TOTAL OF 0.75938E+06 INTEGRATION POINTS.  THIS MAY BE THE CAUSE
     OF THE MEMORY SHORTAGE.  YOU CAN TRY TO REDUCE THE NUMBER OF DIMENSIONS
     OF INTEGRATION OR THE NUMBER OF INTEGRATION POINTS OR USE INTEGRATION=MONTECARLO
     WITH FEWER NUMBER OF INTEGRATION POINTS SUCH AS 500 OR 5000.

[sem_clean_mlr_complex_twolevel.txt](https://github.com/michaelhallquist/MplusAutomation/files/9293987/sem_clean_mlr_complex_twolevel.txt)

**Comment by sda030** [comment]
Another one.
[imputed_input_data.txt](https://github.com/michaelhallquist/MplusAutomation/files/9307184/imputed_input_data.txt)

**Comment by sda030** [comment]
Another fatal error not captured:
*** FATAL ERROR

     PROBLEM OCCURRED DURING THE DATA IMPUTATION.

     THE CONVERGENCE CRITERION IS NOT SATISFIED.
     INCREASE THE MAXIMUM NUMBER OF ITERATIONS OR INCREASE
     THE CONVERGENCE CRITERION.
[stu_cyc1_best_reg_twolevel_v3.txt](https://github.com/michaelhallquist/MplusAutomation/files/9591171/stu_cyc1_best_reg_twolevel_v3.txt)

**Comment by cjvanlissa** [comment]
Thank you for these examples, @sda030
