### ISSUE TITLE
readModels return Warning message: In length(covcoverageSubsections) == 0 || is.na(covcoverageSubsections) :  'length(x) = 4 > 1' in coercion to 'logical(1)'

### ISSUE THREAD

**Issue by haozhou1988** [michaelhallquist/MplusAutomation#177]
fit <- MplusAutomation::readModels(“mplus1001.out”, recursive = T)
It returns warnings. 
![1663123775411](https://user-images.githubusercontent.com/5347702/190047436-bf5ff830-0fd9-4cdc-9381-3e74a7762893.png)
[mplus1001.txt](https://github.com/michaelhallquist/MplusAutomation/files/9562223/mplus1001.txt)

**Comment by haozhou1988** [comment]
I think the reason is that R 4.20 changes the if ( ) rules. see the link: https://stackoverflow.com/a/72848495

**Comment by cjvanlissa** [comment]
@michaelhallquist @JWiley I pushed a fix and did a cursory check for other && / || statements that could become vectorized, but didn't immediately see any. I think we need to be mindful of similar errors in the near future.

**Comment by michaelhallquist** [comment]
Thanks for this patch, @cjvanlissa. I'll keep an eye out for the length warnings that result from assuming one match/scalar when many are returned.
