### ISSUE TITLE
Possible to iterate over classes with different variance structures?

### ISSUE THREAD

**Issue by reytla** [michaelhallquist/MplusAutomation#180]
Dear all,

I was wondering if it is indeed possible to **iterate** over the **number of classes** in such a way that **each class has a freely estimated mean & variance structure**. As an example, within the mplusObject, in the MODEL statement is it possible for a 1 class model to be created such that:

MODEL:
 %c#1%
      [X1-X10];    
      X1-X10;     

**and a 2-class model will be:**

MODEL:
 %c#1%
      [X1-X10];    
      X1-X10;   

 %c#2%
      [X1-X10];    
      X1-X10;

**Comment by cjvanlissa** [comment]
Yes, this is what `createMixtures()` does. Check the documentation!
