### ISSUE TITLE
Some problem with detecting fastDummies being installed (macOS, Macports)

### ISSUE THREAD

**Issue by barracuda156** [michaelhallquist/MplusAutomation#186]
I get this when running check:
```
* checking package dependencies ... ERROR
Package required but not available: ‘fastDummies’

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.
* DONE

Status: 1 ERROR
```
Yet it is installed in fact:
```
10:~ svacchanda$ port -v installed R-fastDummies
The following ports are currently installed:
  R-fastDummies @1.6.3_0 (active) requested_variants='' platform='darwin 10' archs='noarch' date='2023-04-24T16:48:27+0800'
```
Any idea why it cannot find specifically this dependency?

**Comment by michaelhallquist** [comment]
I don't quite know why that would happen, but it's not an issue with MplusAutomation per se. The package dependency checks happen as a standard part of package installation and are handled at the base R level. I wonder if the `.libPaths()` for your installation are not correct and do not point to the location of where MacPorts placed fastDummies? I'd try `library(fastDummies)` in an R session and also `installed.packages()["fastDummies",]` to see if R registers the package installation and location.

Hope this helps,
Michael

**Comment by barracuda156** [comment]
@michaelhallquist Thank you, you are right, something is broken with `fastDummies`:
```
> library(fastDummies)
Error in library(fastDummies) : there is no package called ‘fastDummies’
```
Could you say where `libPaths` are usually set? It turned out that several packages are broken in this manner (not many, but more that one).

**Comment by michaelhallquist** [comment]
If you have non-standard locations for your R packages, you can use the .libPaths function. For example, in my lab, we use this to have a central location for all packages. I place this code in `~/.Rprofile` so that it runs when R starts:

```
rv <- R.Version()
if (rv$major == "4" && rv$minor == ".0.3") {
  lab_packages <- "/proj/mnhallqlab/lab_resources/lab_rpackages_v403"
} else if  (rv$major == "4" && rv$minor == ".1.2") {
  lab_packages <- "/proj/mnhallqlab/lab_resources/lab_rpackages_v412"
} else if  (rv$major == "4" && rv$minor == ".2.1") {
  lab_packages <- "/proj/mnhallqlab/lab_resources/lab_rpackages_v421"
} else {
  lab_packages <- NULL
}

if (!is.null(lab_packages) && !lab_packages %in% .libPaths()) {  .libPaths(c(lab_packages, .libPaths())) }
```

**Comment by barracuda156** [comment]
Any idea what this means? (Sorry, should have checked this straight-away, this sounds at least more specific.)
```
> installed.packages()["fastDummies",]
Error in installed.packages()["fastDummies", ] : subscript out of bounds
```

**Comment by michaelhallquist** [comment]
Probably that R doesn't see the package at all at the moment. You can drop the row subset to see all installed packages: `installed.packages()`

**Comment by barracuda156** [comment]
> Probably that R doesn't see the package at all at the moment. You can drop the row subset to see all installed packages: `installed.packages()`

@michaelhallquist Found the reason, thank you again.

P. S. For anyone bumping into this: https://trac.macports.org/ticket/67299
