### ISSUE TITLE
Extract standardized coefficient

### ISSUE THREAD

**Issue by linem7** [michaelhallquist/MplusAutomation#193]
Hi Michael,

First and foremost, I want to extend my heartfelt thanks for your significant contribution to bridging Mplus and R. Your work has been instrumental in my research, and I cannot express enough how valuable it has been.

However, while using MplusAutomation, I encountered an issue where texreg::screenreg() seems unable to obtain the standardized scores for the model. In the process of parsing the results, I set output: stand in MplusObject, and I can see the standardized scores stored in fit$results$parameters$stdyx.standardized. I'm unsure how to proceed and would be immensely grateful if you could provide some guidance.

Your assistance in helping me obtain this information would be truly appreciated, and I thank you in advance for your time and support.

**Comment by michaelhallquist** [comment]
Sorry for the lag here. But, you should use `type="styx"` as an argument to screenreg, like the example below. Hope this helps!

Michael

```
test <- mplusObject(
  TITLE = "test the MplusAutomation Package;",
  MODEL = "
    mpg ON wt hp;
    wt WITH hp;",
  OUTPUT = "STANDARDIZED;",
  usevariables = c("mpg", "wt", "hp"),
  rdata = mtcars)

res <- mplusModeler(test, "mtcars.dat", modelout = "model1.inp", run = 1L)

extract(res$results)
# there is also a method for mplusObject class
extract(res)

library(texreg)
screenreg(res)
screenreg(res, type = 'stdyx')
```
