### ISSUE TITLE
^metacharacter for PCRE in filefilter does not work as intended.

### ISSUE THREAD

**Issue by AlexandreGareau** [michaelhallquist/MplusAutomation#194]
I wish to use filefilter regex to select only the .out that starts by a numeric character. I tried this `^[0-9]` but it does not work.

I realized that the filefilter argument might not be accepting `^` as a metacharacter because that in `getOutFileList()` there is a `grep()` function that already implements some baseline PCRE code for the filter. Therefore  `.*` is already put at the begining of any filefilter. The `^` metacharacter for specifying to look for the first character does not work.

`
        outfiles <- outfiles[grep(paste(".*", filefilter, 
          ".*", sep = ""), dropOutExtensions, ignore.case = TRUE, 
          perl = TRUE)]
`

Well that is what I think the problem is but then I tested the regex here [regex test](https://regex101.com/r/CThdtC/1)
It should works but I receive this error

`
Warning message:
In getOutFileList(target, recursive, filefilter) :
  No output files detected in this directory.
`
If a take the `^` out of the regex. The r`eadModels() `function works, but the filefilter includes output that have a number other than the first character.

**Comment by michaelhallquist** [comment]
This was fixed in commit 821011d. You can now used meta-characters (^ and $) to mark the beginning and end of the match. In addition, readModels now has a `pathfilter` argument for filtering paths, while `filefilter` now only pertains to the file names.
