### ISSUE TITLE
More information from output file: e.g. confidence intervals and R square?

### ISSUE THREAD

**Issue by johnfrombluff** [michaelhallquist/MplusAutomation#21]
Thank you very much for your work on the Mplus Automation package for R.  I have been enjoying using it immensely.    I wonder whether there are any plans to expand the coverage of extracting data from the Mplus output files.  In particular, for my work it would be very useful to have additional R objects that hold:
1. standardised confidence intervals
2. R-squares
3. Indirect effects

Are there any plans to address any of these issues?  If not, can someone point me to some code to get me started on working on this myself, with the aim of contributing back?  But I warn you: I'm a pretty crappy coder!

Thanks again for this great package,

John

**Comment by dadrivr** [comment]
Any progress on the ability to read indirect effects from the output?

**Comment by CatherineHDemers** [comment]
I too am also interested in extracting the indirect results, has any recent development been made?

**Comment by JWiley** [comment]
@dadrivr @CatherineHDemers Sadly not yet.  AFAIK, Mplus has not yet added indirect effects output into gh5 files, and I do not think that @michaelhallquist  or I have had time to try to do the coding to extract them directly from text.

**Comment by michaelhallquist** [comment]
The three features originally requested by John (standardised confidence intervals, R-squares, and Indirect effects) have all been implemented in the development version of MplusAutomation.
