### ISSUE TITLE
Data Imputation command

### ISSUE THREAD

**Issue by peterhilpert** [michaelhallquist/MplusAutomation#24]
Hi Michael, hi Josh, 

I have a question about the data imputation command. I have a model with runs without problem in MPlus. However, for some analysis I have to include the the data imputation command in MPlus: 

DATA IMPUTATION:
impute f0f f0fl1 f0fl2 f0fl3 f0fl4 f0m f0ml1 f0ml2 f0ml3 f0ml4;
ndatasets=10;    

I tried to use this in MplusAutomation as well, as I use a for loop to run to model for many groups: 

DATA IMPUTATION =  " 
  impute f0f f0fl1 f0fl2 f0fl3 f0fl4 f0m f0ml1 f0ml2 f0ml3 f0ml4;
  ndatasets=10;    ", 

But if I do this, I get errors. 
Error: unexpected symbol in "  if sf" - and if is the latent intercept and sf the latent slope in a growth curve model. What is wrong in my data imputation command? 

Thanks for your support, 
Best, 
Peter

**Comment by JWiley** [comment]
Answered on the Google group:
https://groups.google.com/d/msg/mplusautomation/sr1AfsTSjCI/37R72vErCdIJ

Also support for multiply imputed data was added in:
8aff3c6506a43df1263e9a98276b96c67e0bbd44
