### ISSUE TITLE
Error - More than one match found for parameter

### ISSUE THREAD

**Issue by JonathonLittle** [michaelhallquist/MplusAutomation#27]
Dear Michael,

First of all.  Mplus Automation is a fantastic utility - it has been extremely helpful in automating the running of dozens of models which is very handy.  I can literally run models while I sleep.  Are you able to assist with the following...

I am having problems extracting summary statistics using the command:

> mySummariesA <- extractModelSummaries("D:/Longitudinal/Models/Test Folder", recursive=TRUE)

I receive the following error:

Error in extractValue(pattern = thisField$regexPattern, sectionText, filename,  : 
  More than one match found for parameter: Number of Free Parameters
  D:/Longitudinal/Models/Test Folder/model one - configurable.out

Presumably for the type of model I am trying to retrieve the command is unable to parse out multiple instances of 'Number of Free Parameters' of which there are 2.  The type of model is...

ANALYSIS:
PROCESSORS=4;
ESTIMATOR = MLR;
TYPE= COMPLEX;

Is there a way to filter out this field 'Number of Free Parameters' so that the command doesn’t encounter this match problem?

Many thanks for your assistance,

Jonathon

**Comment by michaelhallquist** [comment]
Hi Jonathon,

If you email me your output (or attach here), I can take a look at what aspect of the output is triggering this problem.

Best,
Michael

**Comment by JonathonLittle** [comment]
Hi Michael,

 

Thank you for your prompt reply.  I have attached the offending output file.

 

Kind regards,

 

Jonathon

**Comment by JonathonLittle** [comment]
Hi Michael,

Did you have any success in identifying the source of the problem?  I sent the requested output your gmail address as listed on the Mplus web page. I seemed unable to figure out how to post it here.

Best,

Jonathon

**Comment by michaelhallquist** [comment]
Hi Jon,

I just looked at the problem. readModels should now handle such outputs (that have an auxiliary part). The $summaries$Parameters field will continue to continue the Number of Free Parameters output, whereas the $summaries$ParametersWithAux will be the Number of Free Parameters within the section Information Criteria Including the Auxiliary Part. I just committed this change to Github, so you can install the development version following the instructions there.

Best wishes,
Michael

**Comment by JonathonLittle** [comment]
Hi Michael,

Hey that works great.  Thanks you very much indeed.  I extracted the summary fit statistics into an HTML table and notice that it truncates the output to the second decimal place on the CFI and TLI (for example).  Is there a way to get it to extract to the 3rd decimal place as it appears in the Mplus output files?

mySummaries <- extractModelSummaries("C:/Models/Single Time Waves", recursive=TRUE)

HTMLSummaryTable(mySummaries, filename="C:/MyModelSummary.html", display=TRUE, keepCols=c("Title",  "SRMR", "CFI", "TLI", "RMSEA_Estimate",  "Observations"), sortBy="Title") 

Kind regards,

Jonathon

**Comment by JonathonLittle** [comment]
Actually not to worry Michael, I can merely do the following with R package xlsx

write.xlsx(mySummaries, "c:/mydata3.xlsx")

and read it in using MS Excel

Many thanks again for making MplusAutomation available to the masses

Jonathon

**Comment by JWiley** [comment]
Closed by @michaelhallquist with 498efc5dcd00cd896b95e1346b184538724f1b24
