### ISSUE TITLE
Another model output that gets confused with more than one match found for #Number of free parameters

### ISSUE THREAD

**Issue by JonathonLittle** [michaelhallquist/MplusAutomation#30]
Hi Michael,

You will recall fixing a similar kind of error a few weeks back for models of TYPE COMPLEX that used auxiliary missing data covariates.  Thank you kindly your help with that request.  Well I have expanded these models to now include tests for invariance which (as luck would have it) now produce a similar error associated with  more than one instance of ^Number of Free Parameters.  The error associated with the following command is shown below...

mySummariesA <- extractModelSummaries("D:/Longitudinal/Models/Invariance Models", recursive=TRUE)

Error in extractValue(pattern = thisField$regexPattern, sectionText, filename,  : 
  More than one match found for parameter: ^Number of Free Parameters

I feel guilty imposing on your time, however if I send through a sample output file is it feasible to look into this when time permits.

With many thanks,

Jonathon

**Comment by michaelhallquist** [comment]
Hi Jonathan,

Feel free to send along another output file and we’ll take a look at it… Hopefully it’s a quick fix.

Michael

**Comment by JonathonLittle** [comment]
Hi Michael,

Sorry for my slow reply.  I just checked this again and it now appears to be working - the problem occurred with multigroup models with auxiliary variables.  I think that subsequent changes that you must have committed to Github since my first post have fixed the error.  

Many thanks,

Jonathon
