### ISSUE TITLE
Extracting model summaries from multiple imputation results

### ISSUE THREAD

**Issue by LechAttack** [michaelhallquist/MplusAutomation#38]
I discovered an issue with extracting model summaries from Mplus outputs based on multiply imputed datasets.

When applied to an mplusObject with imputed = T, `mplusModeler ` returns an error message:

`modelout <- mplusModeler(model, modelout = "model.inp", run= 1)`
> In detectColumnNames(filename, modelSection, sectionType) :
>   Unable to determine column names for section model_results

Consequently, both `screenreg() ` and `summary()` as applied to the output return an error message:
`summary(modelout)`
> Error in sprintf("Model: Chi2(df = %s) = %s, p = %s \n", ChiSqM_DF, ChiSqM_Value,  : 
>   object 'ChiSqM_Value' not found

The problem appears to lie solely in the extraction of the model summaries from the output.
For example, `screenreg(modelout)` without calling for model summaries (e.g., only requesting model parameters but not model fit) works, but `screenreg(modelout, summaries = c('CFI', 'TLI'))` does not.

The reason seems to be that the names in `modelout$results$summaries` do not match when the Mplus output is from inputed data. For example, ChiSqM_Value does not exist in `names(modelout$results$summaries)` - there it is called ChiSqM_Mean. Other entries like ChiSqM_PValue do not exist at all.

Is it possible to adapt the `screenreg() `and `summary()` functions to Mplus output based on multiple imputations?

PS: Thanks you much for your work on this amazing package - what a great service to the R community!

**Comment by jhartma** [comment]
I have the very same problem and can confirm that the name selectors don't match for imputed data.
E.g. TLI exists in ```CFI/TLI -> TLI -> Mean``` instead of ```CFI/TLI -> TLI```

It would be really great to have this fixed.

**Comment by michaelhallquist** [comment]
Can you please upload a .out file containing the problematic output? At the moment, Example 11.8 from the user's guide works for me without a problem.

[ex11.8part2.txt](https://github.com/michaelhallquist/MplusAutomation/files/853566/ex11.8part2.txt)

Best,
Michael

`> library(MplusAutomation)
> x <- readModels("ex11.8part2.out")
> x$summaries

  Mplus.version
1          7.31
                                                                                                                       Title
1 this is an example of a two-level multiple indicator growth model with categorical outcomes using multiple imputation data
  AnalysisType   DataType Estimator Parameters ChiSqM_DF ChiSqM_Mean ChiSqM_SD ChiSqM_NumComputations CFI_Mean CFI_SD
1     TWOLEVEL IMPUTATION     WLSMV         25        65       57.06     1.635                      5        1      0
  CFI_NumComputations TLI_Mean TLI_SD TLI_NumComputations RMSEA_Mean RMSEA_SD RMSEA_NumComputations SRMR.Within_Mean
1                   5    1.011  0.002                   5          0        0                     5            0.043
  SRMR.Within_SD SRMR.Within_NumComputations SRMR.Between_Mean SRMR.Between_SD SRMR.Between_NumComputations        Filename
1          0.005                           5             0.165           0.014                            5 ex11.8part2.out`

**Comment by jhartma** [comment]
Thanks for looking into it. I created a gist [here](https://gist.github.com/jhartma/643e43bc16da151edf6c8e2d4c5ee49e)

I noticed I am on an older version on MPlus, the output looks fairly the same though.

Here is what R gives me:
```
> library(MplusAutomation)
> lang <- readModels("lang_growth.out")
Reading model:  lang_growth.out 
> 
> lang$summaries
  Mplus.version                    Title AnalysisType   DataType Estimator Parameters ChiSqM_DF        Filename
1          6.12 Language Integration v1       GENERAL INDIVIDUAL     WLSMV         37        57 lang_growth.out
```

**Comment by JWiley** [comment]
Just an update (and for my own records).  The issue seems related not to analyzing multiply imputed data, but imputing it and analyzing it in the same model.

**Comment by LechAttack** [comment]
Correct. This issue occurs when analyzing multiply imputed datasets from a file as in Mplus example 13.13:
DATA: FILE IS implist.dat; TYPE = IMPUTATION;

I have not checked whether it also occurs when carrying out imputation and analysis in the same step, as when requesting DATA IMPUTATION.

Best wishes,
Clemens

**Comment by michaelhallquist** [comment]
Hi all,

Thanks for the additional detail. Mplus has been inconsistent in how it outputs model summaries in this sort of output. I believe such files in Mplus v8 print out in the typical format (without means and SDs for summaries), but that older versions did not. I've now implemented a workaround that tries to detect the output format. It seems to work for your output (i.e., the summaries are now extracted), so please install the development version and let me know if you have other problems.

Thanks,
Michael
