### ISSUE TITLE
mplusObject function does not accept some of MonteCarlo Simulation Arguments

### ISSUE THREAD

**Issue by serdarcaglak** [michaelhallquist/MplusAutomation#43]
MplusObject still does not accept the following arguments:

MONTECARLO:
NAMES ARE
NOBSERVATIONS =
SEED = 
NREPS=
MODEL POPULATION:
PROC =
fbiter =

Please, pay attention to the command ending whether it requires ":" , "=", or nothing afterwards. 
Also, make sure that the following Mplus code is accepted by the MplusObject once you make the necessary enhancements in the package:

TITLE: Bayesian CFA Monte Carlo;
MONTECARLO:
NAMES ARE y1-y10;
NOBSERVATIONS = 50;
NREPS = 1000;
SEED = 53487;

MODEL POPULATION:
f1 BY y1-y5*.7;
f2 BY y6-y10*.7;
f1@1 f2@1;
y1-y10*.51;
f1 WITH f2*.30;
ANALYSIS:

ESTIMATOR = BAYES;
PROC = 2;
fbiter = 10000;

MODEL:
f1 BY y1-y5*.7 y6*.3  (a1-a6);
f2 BY y5*.3 y6-y10*.7 (b1-b6);
f1@1 f2@1;
y1-y4*.51 y5-y6*.42 y7-y10*.51;
f1 WITH f2*.30 (c1);

MODEL PRIORS:
a1-a5~N(.4,.05);
a6~N(.2,.5);
b1~N(.2,.5);
b2-b6~N(.4,.05);
c1~N(.20,.01);

OUTPUT:
TECH9;​

**Comment by JWiley** [comment]
@serdarcaglak   Does this example from the `mplusModeler()` man pages work for you?  `mplusObject()` is not designed to take as argument each possible option to Mplus.  Rather it takes *sections*, so:

TITLE
MONTECARLO
MODEL POPULATION
ANALYSIS
MODEL
MODEL PRIORS
OUTPUT

and then within each section, you give it a character string containing the pertinent code for Mplus.

````
# Monte Carlo Simulation Example

montecarlo <- mplusObject(
 TITLE = "Monte Carlo Example;",
 MONTECARLO = "
  NAMES ARE i1-i5;
  NOBSERVATIONS = 100;
  NREPS = 100;
  SEED = 1234;",
 MODELPOPULATION = "
  f BY i1-i5*1;
  f@1;
  i1-i5*1;",
 ANALYSIS = "
  ESTIMATOR = BAYES;
  PROC = 2;
  fbiter = 100;",
 MODEL = "
  f BY i1-i5*.8 (l1-l5);
  f@1;
  i1-i5*1;",
 MODELPRIORS = "
   l1-l5 ~ N(.5 .1);",
 OUTPUT = "TECH9;")

fitMonteCarlo <- mplusModeler(montecarlo,
  modelout = "montecarlo.inp",
  run = 1L,
  writeData = "always",
  hashfilename = FALSE)
````

**Comment by serdarcaglak** [comment]
Now, I got it, Josh! I noticed where my mistake was. It works perfect now.

Thank you so much :)

**Comment by JWiley** [comment]
Great, glad to hear it! :)
