### ISSUE TITLE
readModels error with proportional odds model

### ISSUE THREAD

**Issue by wepelham3** [michaelhallquist/MplusAutomation#46]
1. I'm fitting a multilevel growth model with an ordinal categorical outcome.
2. Mplus (v7.4) includes results from a "BRANT WALD TEST FOR PROPORTIONAL ODDS" directly below the MODEL RESULTS section.
3. Results from the BRANT WALD TEST are incorrectly appended to the `.$parameters` component, like in rows 13 thru 19 here:

```
> readModels("mplus-dummy-file.out")$parameters
Reading model:  mplus-dummy-file.out 
$unstandardized
          paramHeader        param     est      se     est_se         pval BetweenWithin
1             TRAJ.ON       TX_BIN  -0.187   0.167     -1.119        0.263       Between
2            P_IRS.ON       TX_BIN   0.263   0.372      0.706         0.48       Between
3          P_IRS.WITH         TRAJ   0.061   0.178      0.343        0.732       Between
4          Intercepts         TRAJ   -0.32   0.139     -2.298        0.022       Between
5          Thresholds      P_IRS$1   -4.15   0.375    -11.068            0       Between
6          Thresholds      P_IRS$2  -2.561   0.325     -7.873            0       Between
7          Thresholds      P_IRS$3  -1.536   0.309     -4.972            0       Between
8          Thresholds      P_IRS$4  -0.217   0.296     -0.733        0.464       Between
9          Thresholds      P_IRS$5   1.048     0.3      3.494            0       Between
10         Thresholds      P_IRS$6   2.903   0.332      8.746            0       Between
11 Residual.Variances        P_IRS   3.159   0.637      4.961        0.000       Between
12 Residual.Variances         TRAJ   0.297   0.110      2.708        0.007       Between
13 Residual.Variances        BRANT    WALD    TEST        FOR PROPORTIONAL       Between
14 Residual.Variances      Degrees      of Degrees         of      Degrees       Between
15 Residual.Variances   Chi-Square Freedom P-Value Chi-Square      Freedom       Between
16 Residual.Variances        P_IRS   P_IRS   P_IRS      P_IRS        P_IRS       Between
17 Residual.Variances      Overall    test   7.466         10        0.681       Between
18 Residual.Variances TIMESCALE_P_   4.002       5      0.549 TIMESCALE_P_       Between
19 Residual.Variances       TX_BIN   3.504       5      0.623       TX_BIN       Between
```

It does throw a warning to indicate something is wrong:

    Warning message:
    In rbind(c("P_IRS", "3.159", "0.637", "4.961", "0.000"), c("TRAJ",  :
      number of columns of result is not a multiple of vector length (arg 1)

[Here](https://github.com/michaelhallquist/MplusAutomation/files/949419/mplus-dummy-file.txt) is an output file that illustrates the issue.  Please let me know if you need anything else.

**Comment by michaelhallquist** [comment]
Hi Will,

Thanks for the output file. We hadn't encountered that output section before, so it wasn't caught in the section parser. I've amended the corresponding function and your output file now reads in properly. The Brant Wald is not parsed yet, but at least the parameters section is handled as expected.

You'll need to install the development version of the package to get this update: https://github.com/michaelhallquist/MplusAutomation. The change will be rolled into the next CRAN update in the next month or so.

Best,
Michael

**Comment by wepelham3** [comment]
Perfect, thanks!
