### ISSUE TITLE
Github installation error on Mac: object ‘choose.dir’ is not exported by 'namespace:utils'

### ISSUE THREAD

**Issue by jaohar** [michaelhallquist/MplusAutomation#48]
Hello,
I am unable to install the development version of MplusAutomation from github using the command:
install_github("michaelhallquist/MplusAutomation")

* installing *source* package ‘MplusAutomation’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error : object ‘choose.dir’ is not exported by 'namespace:utils'

I am using R version 3.4 on Mac OS X. ‘choose.dir’ appears to be a Windows only function. I am able to use the previous release version of MplusAutomation. Please let me know if I am doing something wrong.

Thank you for your time.

-Jonathan

**Comment by JWiley** [comment]
@jaohar I've just committed an attempted patch.  I don't have a mac, but could you test whether it is working now or not?

**Comment by jaohar** [comment]
Thank you for the very quick response. Yes, this installs without error now. sessionInfo() reports the version as MplusAutomation_0.6-4. Is that correct?

**Comment by JWiley** [comment]
@jaohar Yes that's correct for now.  We normally update the version when we are releasing a new version.
