### ISSUE TITLE
readModels Error: subscript out of bounds

### ISSUE THREAD

**Issue by jaohar** [michaelhallquist/MplusAutomation#50]
Hello,
I get the following error message when importing the attached Mplus output file. I am using R 3.4, the development version of MplusAutomation, and the latest version of Mac OS X.

`"Error in `[<-`(`*tmp*`, rownames(l), colCounter:(colCounter + ncol(l) -  : subscript out of bounds"`

Thank you for your time.

-Jonathan

[HLQ7NHS_CM1_OVERALL.out.txt](https://github.com/michaelhallquist/MplusAutomation/files/1031660/HLQ7NHS_CM1_OVERALL.out.txt)

**Comment by michelow** [comment]
Same here. Note, for me, the error message is:
<pre><code>Error in `[<-`(`*tmp*`, rownames(l), colCounter:(colCounter + ncol(l) -  : 
  subscript out of bounds</code></pre>

I'm running R 3.33 on Windows 8.1 and - perhaps most importantly - using the latest Mplus 8.0 Base Program and Combination Add-On (64-bit). Am using the templateing automation to run a series of LCA models and the error occurs on the first output file no matter whether I specify to recurse the subfolder hierarchy or give it a single output file for any of the models with numbers of classes (1-7).

Note that extractModelSummaries seems to work fine, so far only readModels gives the error message.

Mplus output for 1-class model attached.
[1_class_lca_nocovs_nogrp.out.txt](https://github.com/michaelhallquist/MplusAutomation/files/1103578/1_class_lca_nocovs_nogrp.out.txt)

**Comment by stochl** [comment]
the same issue here...readModels givesd this error also for ordinary CFA model

**Comment by stochl** [comment]
Update: I have just updated MplusAutomation to the latest version from github and it solved the issue. Thanks

**Comment by michaelhallquist** [comment]
I have verified that this issue is fixed for both outputs in the development version of MplusAutomation on Github. This will roll out to CRAN as v0.7 soon, or you can install it via the directions on the Github page.

Best,
Michael
