### ISSUE TITLE
Option for multiple instances

### ISSUE THREAD

**Issue by sda030** [michaelhallquist/MplusAutomation#52]
For some models parallelization is not possible (from Mplus' side), and/or high-performance computer cluster might not allow parallelization. In those cases it might be of interest to run multiple instances of Mplus.exe. I suggest a very tiny "experimental feature" which is simply a flip sent to the argument in the `system2(wait=TRUE)` [call](https://github.com/michaelhallquist/MplusAutomation/blob/master/R/runModels.R#L469). More specifically: an argument in `runModels(multipleInstances=1L)` which lets the user specify the number of instances of mplus.exe to run simultaneously (typically somewhere between 1 and number of CPU cores). Since `length(inpfiles)` can be longer than `multipleInstances`, you would need to break up the files into groups using e.g. `inpfiles_list <- suppressWarnings(split(x = inpfiles, f = rep(x = seq_len(multipleInstances), each = length(inpfiles)/multipleInstances)))`, and then place a group-loop on top of the regular for loop (e.g. `for (inpfiles in inpfiles_list) {`). Challenge is that you would need to use your `exitRun()` trick to also keep track of the processes and check (once in a while?) whether they have closed (and admittedly no option for checking Mplus errors within R using this method).  

With some looping and filefiltering the user could do the rest.

**Comment by sda030** [comment]
After attempting to implement this, I realize that the big challenge is to figure out when a particular mplus.exe process is finished executing. As far as I know there is no way of being notified passively; e.g. R must check every 10 seconds or so.

**Comment by JWiley** [comment]
I do something similar, but using a local cluster, see for example the internals of `trainLGMM()`.  Generally works well and is how I implement running many models where its better to run models simultaneously, rather than running multiple cores on one model.

**Comment by sda030** [comment]
I had in mind something that did not rely on the local cluster (these features are blocked on our university cluster service). But I realize that this is too much to ask for given the rare circumstances. And your solution works well in most cases. I withdraw my issue.
