### ISSUE TITLE
prepareMplusData writeData and imputed list

### ISSUE THREAD

**Issue by sda030** [michaelhallquist/MplusAutomation#53]
The option of not rewriting the data to disk unless hash has changed is a great feature. However, it is currently not implemented for the imputed dataset, which is where massive data writing is common (original reason for suggesting the feature). I do not see why not implementing something of the .hashifyFile function in an lapply loop over the imputed datalist and the expected filename(s)? Would not capture changes to the number of imputations in the datalist, but I consider that a very rare case?

I now wait for about 10min each model I run (imputed datasets, different data)

**Comment by JWiley** [comment]
No reason it was not implemented for multiple imputation --- just forgot about that aspect as I rarely analyze imputed data in Mplus.  It will probably be December before I have time to do this, but I will add to my todo list and definitely will implement.

**Comment by sda030** [comment]
'Everyone' working on the international large-scale assessments (PISA, TIMSS, TEDS-M, ICILS, etc) use multiple imputation. as the performance scores are provided as plausible values. Would be nice feature!

**Comment by JWiley** [comment]
@sda030 I believe this is implemented now. Could you please check out the examples in `prepareMplusData()` and check whether the hashing for multiply imputed data works for you? I've tried to make up some tests, but have not robustly tested the feature and as I rarely use multiply imputed data with Mplus, really need you/others to test and give bug reports if you have issues. Hopefully this plus use of `fwrite()` substantially improves your wait time for writing out data.

**Comment by sda030** [comment]
Apologies for late reply, had to finish and submit my PhD thesis. I tried it now with 10-col, 1,000,000 row, 4 imputated sets. The fwrite improvement is massive: from 59sec to 3.3sec. However, the hash check seems small (2.6sec). Seems strange to me that retrieving and comparing the hashes will take that much time when the digest::digest takes 1.2 sec. Though I must say that unless you quickly spot why, I wouldn't spend time on this part. fwrite is far the most important.
Thanks!

**Comment by JWiley** [comment]
@sda030 congratulations on submitting your PhD thesis!
Weird on the hash check, I'll dig a bit, but I'm delighted that the write time has dropped from 59 to 3.3sec. Those are good gains!
