### ISSUE TITLE
Could not find "Log-Likelihood" or other fit statics from readModels()

### ISSUE THREAD

**Issue by Sunflowerpsy** [michaelhallquist/MplusAutomation#55]
Hi, thank you for creating and sharing this very convenient package! 

**Problem**: 
I have trouble in extracting the LL (log-likelihood) with the new function "readModels". 

**What have been done**: 
I list the names from "readModels" output and searched for LL one by one but in vain. 
The "extractModelSummaries" function used to return the "LL" conveniently, but the current package does not support this function any more. 
I tried to read the source document and modify, but could not find the exact code to do it. 

**To-be-solved**: So I wonder whether this package still supports extracting LL. Or, is there a convenient way to do it? Thank you. 

My backup plan is to do it manually, by read in output file, and search for the key word "log-likelihood". However, since I use this nice package to run, and extract other parameters, I hope to make the whole project in a coherent line.

**Comment by michaelhallquist** [comment]
Without a full output file or reproducible example, it's hard to figure out the problem you mention. As far as I know, readModels reads the log-likelihood properly. Here's a quick example using Mplus User's Guide Example 5.27:

`
m <- readModels("ex5.27.out")

print(m$summaries$LL)
[1] -17300.59
``

**Comment by Sunflowerpsy** [comment]
Hi Michael,

I really appreciate your speedy response! I tried the example you mentioned above and it worked well. But it could not work for my output some how. I do not know why. Attached is an example of my output (note: as the attachment does not support a file with suffix as ".out", I change it into ".txt" to be uploadable).  
[Mplus_lcdm_output.txt](https://github.com/michaelhallquist/MplusAutomation/files/1253124/Mplus_lcdm_output.txt)


Thanks!

**Comment by michaelhallquist** [comment]
Hi Sunflowerpsy,

This problem was solved in the development version of the package (July 22) and resulted from part of the TECH10 section being matched as the model fit section. For the time being, please install the development version of the package, as described here: https://github.com/michaelhallquist/MplusAutomation.

Best,
Michael

**Comment by Sunflowerpsy** [comment]
Hi Michael,

Thank you very much for your help! I'll try that! 

Best regards,
Sunflowerpsy
