### ISSUE TITLE
ID Variables in ESEM models

### ISSUE THREAD

**Issue by KostaGav** [michaelhallquist/MplusAutomation#58]
Hi Michael,
I have some issues trying to merge the factor scores of an ESEM model back to my original data frame. When running the model, I am not able to define an id-variable in my model, since the mplusObject function does not properly handle the "VARIABLE = idvariable is ID;" function. Is there any workaround to retrieve the factor scores with my id-variable as an additional column in the same data frame?

Best,
Konstantin

**Comment by JWiley** [comment]
Hi @KostaGav 

This should work in the development version.  Assuming you have the `devtools` package installed, you can install the latest version of MplusAutomation by running:

`devtools::install_github("MichaelHallquist/MplusAutomation")`

I have also added a new example to the `mplusModeler()` function showing how to do this, that you may find useful.

```
# Example including ID variable and extracting factor scores
dat <- mtcars
dat$UID <- 1:nrow(mtcars)

testIDs <- mplusObject(
  TITLE = "test the mplusModeler wrapper with IDs;",
  VARIABLE = "IDVARIABLE = UID;",
  MODEL = "
    F BY mpg wt hp;",
  SAVEDATA = "
    FILE IS testid_fscores.dat;
    SAVE IS fscores;
    FORMAT IS free;",
  usevariables = c("UID", "mpg", "wt", "hp"),
  rdata = dat)

 resIDs <- mplusModeler(testIDs, modelout = "testid.inp", run = 1L)

# view the saved data from Mplus, including factor scores
# the indicator variables, and the ID variable we specified
head(resIDs$results$savedata)

# merge the factor scores with the rest of the original data
# merge together by the ID column
dat <- merge(dat, resIDs$results$savedata[, c("F", "UID")],
  by = "UID")

# correlate merged factor scores against some other new variable
with(dat, cor(F, qsec))

 # remove files
 unlink(resIDs$results$input$data$file)
 unlink("testid.inp")
 unlink("testid.out")
 unlink("testid_fscores.dat")
 unlink("Mplus Run Models.log")
```
