### ISSUE TITLE
readModels and CI's for indirect effects

### ISSUE THREAD

**Issue by IHCWU** [michaelhallquist/MplusAutomation#61]
Hello Michael,

Thank you for developing MplusAutomation. It has been very helpful. 

I may be missing something, but is it possible to extract the confidence intervals for indirect effect estimates? 

Thanks.

**Comment by michaelhallquist** [comment]
Hi there,

We haven't yet implemented extraction of confidence intervals for the indirect effects, but I will add this to the TODO list.

Thanks,
Michael

**Comment by IHCWU** [comment]
Hi Michael,

Thank you for your hardwork!

**Comment by michaelhallquist** [comment]
Hi there,

The development version of the package now supports confidence intervals for indirect effects. The structure of $indirect now mirrors $parameters, so you should see standardized, unstandardized, and confidence interval results in there. This will roll out to CRAN as v0.7-2 shortly.

Michael
