### ISSUE TITLE
Error when using getSavedata_Data with version 0.7-1

### ISSUE THREAD

**Issue by jrosen48** [michaelhallquist/MplusAutomation#63]
First, thanks for a truly outstanding package. I just added a package I have been working on, [**tidyLPA**](https://jrosen48.github.io/tidyLPA/), to the examples page of the Wiki. The package uses **MplusAutomation** to run dynamically-generated syntax for models for Latent Profile Analysis and then reads the output back into R.

I noticed a strange difference between version **0.7** and the **0.7-1** which was just released a few days ago: the `getSavedata_Data()` returns an error when I'm using the new, **0.7-1** version. 

I was able to (temporarily) fix this in the package by specifying in the DESCRIPTION that **0.7** is needed. However, I'm concerned I'm doing something wrong. But, I didn't notice any changes (specifically) to this (`getSavedata_Data()`) function in the NEWS, though there did seem to be a number of changes to functions that read model output.

### Using MplusAutomation 0.7

```
# install.packages("tidyLPA")
library(tidyLPA)
#> tidyLPA provides the functionality to carry out Latent Profile Analysis. Note that tidyLPA is still at the beta stage! 
#> Please report any bugs at https://github.com/jrosen48/tidyLPA or send an email to jrosen@msu.edu.
estimate_profiles_mplus(iris,
                        Sepal.Length, Sepal.Width, Petal.Length, Petal.Width,
                        n_profiles = 2,
                        model = 1)
#> Note that this (and other functions that use MPlus) is at the experimental stage! Please provide feedback at https://github.com/jrosen48/tidyLPA
#> LogLik is 488.915
#> BIC is 1042.968
#> Entropy is 0.991
```

### Using MplusAutomation 0.7-1

Here, I install the new version of **MPlusAutomation** first.

```
install.packages("MplusAutomation")
#> 
#> The downloaded binary packages are in
#>  /var/folders/95/z6jql6w546vd0brdwm722s5r0000gn/T//Rtmptrrb7N/downloaded_packages
library(tidyLPA)
#> tidyLPA provides the functionality to carry out Latent Profile Analysis. Note that tidyLPA is still at the beta stage! 
#> Please report any bugs at https://github.com/jrosen48/tidyLPA or send an email to jrosen@msu.edu.
estimate_profiles_mplus(iris,
                        Sepal.Length, Sepal.Width, Petal.Length, Petal.Width,
                        n_profiles = 2,
                        model = 1)
#> Note that this (and other functions that use MPlus) is at the experimental stage! Please provide feedback at https://github.com/jrosen48/tidyLPA
#> LogLik is 488.915
#> BIC is 1042.968
#> Entropy is 0.991
#> Error in getSection("^\\s*SAVEDATA INFORMATION\\s*$", outfiletext): Standard headers not parsed
```

If you add `remove_tmp_files = FALSE` as an argument as below, then you can see the input and output files (in your working directory). They have the save data output, I think.

```
estimate_profiles_mplus(iris,
                        Sepal.Length, Sepal.Width, Petal.Length, Petal.Width,
                        n_profiles = 2,
                        model = 1, remove_tmp_files = FALSE)
```

Any idea what's going on here? My short-term fix of specifying the (slightly) older version should work, but I'm curious what is going on and would like to help address this if I can. Thank you again for a package that makes my package possible!

**Comment by jrosen48** [comment]
Per a suggestion from [@cjvanlissa](https://github.com/cjvanlissa), I found the savedata in the output of `runModels()` (in the `@savedata`) slot. So, this is all good for me for now, but I'm curious if `getSavedata_Data()` is being deprecated. Thanks!

**Comment by michaelhallquist** [comment]
Hi there,

Yes, getSavedata_Data() was deprecated, but I forgot to mention it when called. It now tells you what to do instead, which is readModels("mplusresults.out", what="savedata")$savedata.

I've fixed this in the dev version, which will roll out to CRAN shortly.

Michael
