### ISSUE TITLE
Standardized indirect effects with readModels

### ISSUE THREAD

**Issue by beichmann** [michaelhallquist/MplusAutomation#64]
Dear Michael,

thank you for yout great R-Package. It is extremely helpful.
I have a question: Does readModels also provide standardized indirect effects (like in the Mplus output) or only the unstandardized ones? And if it does provide standardized indirect effects, where can I find them?

Thank you very much,
Beate

**Comment by michaelhallquist** [comment]
At present, it only reads the unstandardized effects. I'm working on an update to get standardized, too. It shouldn't take much time since the core parser is already written. I'll post back here and close the issue once that's working.

Michael

**Comment by michaelhallquist** [comment]
Hi Beate,

FYI, the development version on Github now supports standardized indirects in the $indirect element of readModels. This will roll out to CRAN as v0.7-2 shortly.

Michael
