### ISSUE TITLE
How to create class-specific code in LCA/LPA

### ISSUE THREAD

**Issue by HeikoBreitsohl** [michaelhallquist/MplusAutomation#66]
Hi Michael,

thanks for creating this great package!

Is there a way of generating class-specific Mplus commands in the MODEL section of each model?

I am thinking of something like a loop that will add the appropriate number of %c#% commands to each model. 
For example, in a series of LCA/LPA models, the 2-class model would get a %c#1% and a %c#2% line in the MODEL section (in order to freely estimate parameters across classes), while the 3-class model would get a %c#1%, a %c#2%, and a %c#3% line.

Thanks so much!

Best,
Heiko

**Comment by cjvanlissa** [comment]
Dear Heiko, this functionality - and other enhancements for mixture/latent class models - is available in my fork of MplusAutomation, and is currently under review for potential integration into the main package. If you want to beta test my code, you can run install_github("cjvanlissa/MplusAutomation"). I'm open for feature requests!

**Comment by HeikoBreitsohl** [comment]
Thanks for the quick reply!
I guess this will tell you how familiar I am with R, but is there documentation about the new commands in the beta version?
[By the way, nice presentation at the S4 conference!]

**Comment by cjvanlissa** [comment]
Yes, everything is documented with examples! After installing from GitHub, run ?createMixtures, and you will see the documentation for that function. Thank you for the compliment, such a small world eh :)

**Comment by michaelhallquist** [comment]
I agree that Caspar's functions are an easier way to do this. You can use the conditional tags to create these sections across models. I've uploaded an old template file that I think approximates what you're trying to do.

Best,
Michael

[LSPD Template.txt](https://github.com/michaelhallquist/MplusAutomation/files/1882199/LSPD.Template.txt)
