### ISSUE TITLE
Warning for createModels()

### ISSUE THREAD

**Issue by HeikoBreitsohl** [michaelhallquist/MplusAutomation#67]
Hi Michael et al.,

when running createModels(), I get the following warning:
In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'

Does this have to do with the fact that I used "MISSING = 999" in the Mplus code template?

Either way, what can I do to fix this?

Thanks!!
Heiko

**Comment by michaelhallquist** [comment]
Not too sure, Heiko. Could you upload the template file here as a .txt file?

Thanks,
Michael

**Comment by HeikoBreitsohl** [comment]
Sure thing.
It seems the problem is something else, because I fixed the MISSING label, but still get the warning.

Thanks so much!

[HSG_Automate_LPA.txt](https://github.com/michaelhallquist/MplusAutomation/files/1844377/HSG_Automate_LPA.txt)

**Comment by cjvanlissa** [comment]
You're using the template syntax incorrectly. Here's an example that I think should work (below). PS I think you might enjoy the functions createMixtures() and plotMixtures() in my fork of MplusAutomation! They are designed to do exactly what you're trying to accomplish, automatically.

```
[[init]]
iterators = class;
class=1:10;
filename="[[class]] class LPA.inp";
outputDirectory = "C:/Users/hebreitsohl/Seafile/Meine Bibliothek/Paper/HSG/HSG_LPA";
[[/init]]

TITLE: [[class]] class LPA
DATA:   
FILE = "C:/Users/hebreitsohl/Seafile/Meine Bibliothek/Paper/HSG/HSG_2019_FS.txt";
VARIABLE: 
NAMES = A01_1 A01_2 A01_3 A01_4 A01_5 A01_6 A02_1 A02_2 A02_3 A03_7 A03_8 A03_9 ID A02_4 A02_5 A02_6 
A02_7 A02_8 A02_9 A02_10 A03_4 A03_5 A03_6 A05 A10A A10 B01_9 B01_10 B01_11 B01_12 B01_16 B01_17 B01_18 B01_19 
B02_5 B02_6 B02_7 B02_8 B02_9 B02_10 B02_11 C06_1 C06_2 C06_3 C12 C08 C22_1 C22_2 C22_3 C22_4 C22_5 PROBSO 
PROBSO_SE INFPRO INFPRO_SE INTERD INTERD_SE TDEM TDEM_SE;

USEVAR = PROBSO INFPRO INTERD TDEM;
MISSING = ALL (999);
IDVAR = ID;
                                             
CLASSES = c([[class]]);
                       
ANALYSIS:
  TYPE IS MIXTURE;
  ESTIMATOR IS MLR;
  STARTS = 10000 400;
  STITERATIONS = 400;
  CONVERGENCE = 0.000001;
  LRTSTARTS = 0 0 100 20;

MODEL:
%OVERALL%
OUTPUT:
  SAMPSTAT CINTERVAL RESIDUAL TECH1 TECH7 TECH11 TECH14;
PLOT:
  TYPE = PLOT3;
```

**Comment by michaelhallquist** [comment]
Thanks, Caspar. I agree that Heiko's copy didn't follow the proper syntax for createModels. The one you uploaded looks correct. I'm closing this for now, but please re-open if you are still having issues.

Michael
