### ISSUE TITLE
Model fit improvement not extracted for invariance models

### ISSUE THREAD

**Issue by sda030** [michaelhallquist/MplusAutomation#71]
When running the new invariance convenience feature in Mplus, the Models Compared information is not extracted.
Another, very minor detail is that the object shows the parameters in a bit convoluted structure:
`$parameters$unstandardized$CONFIGURAL.MODEL$unstandardized`
(i.e. unstandardized twice).

(Wish I could make a pull request but I am busy writing up thesis.)
[example.txt](https://github.com/michaelhallquist/MplusAutomation/files/2068582/example.txt)

**Comment by cjvanlissa** [comment]
Dear sda030, I have written a potential fix to this issue. Would you be so kind as to try extracting the models compared information again after installing my fork of MplusAutomation? To install, run:

library(devtools)
install_github("cjvanlissa/MplusAutomation")

**Comment by sda030** [comment]
Hi cjvanlissa, I tried but got 
`readModels(target = "example.out")
Reading model:  m_PCK_1PL_invariance_ML.out 
Error in model_rows[, 1] : subscript out of bounds`
I checked that the file can be read using original MplusAutomation installation.

Not sure if the function below is supposed to work, but it didn't either:
`MplusAutomation:::extractParameters_1file("example.out")
Error in getSection("^MODEL RESULTS$", outfiletext) : 
  Standard headers not parsed`

**Comment by cjvanlissa** [comment]
Thank you very much for testing this! I'm a bit puzzled, because when I install my own package from Github and run it on the example.txt (renamed to .out) you posted earlier, I get this:

```
    > results <- readModels("C:/Users/lissa102/Documents/test/example.out")
    Reading model:  C:/Users/lissa102/Documents/test/example.out 
    > results$invariance.testing
    $`models`
               Chi-Square DF Pvalue
    Configural    162.268 70      0
    Metric        154.469 88      0
    Scalar        165.168 97      0
    
    $compared
                              Chi-Square DF Pvalue
    Metric against Configural     16.750 18 0.5403
    Scalar against Configural     28.051 27 0.4083
    Scalar against Metric         12.249  9 0.1996
```
Any chance you changed the data file? If so, could you send me the one you're using?

**Comment by sda030** [comment]
Apologies, the file had been overwritten with something else... Yes, it works now. Could I be requesting a column name for the column with "Configural Metric Scalar" etc in both the tables? That would be more in line with tidyverse practice and then easier to join multiple models. 
Thanks a lot for this!

**Comment by cjvanlissa** [comment]
Thank you for checking!

> Could I be requesting a column name for the column with "Configural Metric Scalar" etc in both the tables? 

Currently, the tables are numerical matrices. The "Configural Metric Scalar" stuff are rownames. I could also return them as data.frames, with a column with the names. @michaelhallquist what would you prefer?

**Comment by michaelhallquist** [comment]
Sorry to lose track of this, but I think it has been handled reasonably by moving your code to the extractInvarianceTesting function. I think the current format (rownames in a matrix) works reasonably well. I'm closing this for now since the functionality seems to work (have tried on several outputs), but feel free to re-open if I'm missing something.
