### ISSUE TITLE
readModels section for indirect effects mislabeled

### ISSUE THREAD

**Issue by cjvanlissa** [michaelhallquist/MplusAutomation#73]
The first three columns of the model indirect section are labeled "pred", "intervening", and "outcome". However, pred and outcome are the wrong way around. Also, there's a case to be made for calling these paramHeader and param, so downstream functions developed for the main parameters section can be applied to this section of the output too.

**Comment by michaelhallquist** [comment]
Thanks for noticing this. I've switched the pred/outcome mismatch for the $specific sections. I'm going to leave the naming as pred/outcome since param and paramHeader nomenclature may become confusing if we try to use it for this.
