### ISSUE TITLE
Extracting Factor Scores from Mplus

### ISSUE THREAD

**Issue by leonpwendt** [michaelhallquist/MplusAutomation#77]
Hello MplusAutomation Team,

When trying to extract factor scores from the Mplus output ...
`extractFacScoreStats("latent_mlvar.out")`

.. I got the error message that the function could not be found.
> Error in extractFacScoreStats("latent_mlvar.out") : 
>   could not find function "extractFacScoreStats"

Can you help me?
Thanks for your work. I appreciate MplusAutomation very much. 

Leon Wendt

**Comment by michaelhallquist** [comment]
Hi Leon,

That function is not part of the user interface for the package (it's just internal). To get the factor score statistics, look at the `fac_score_stats` element of the object created by `readModels`.

Best,
Michael
