### ISSUE TITLE
mplusObject cannot read DATA TWOPART option

### ISSUE THREAD

**Issue by bew003** [michaelhallquist/MplusAutomation#84]
Hi, I am trying to use the DATA TWOPART option in an mplusObject, but I can't seem to get it to run after trying several syntax variations. I've attached a reproducible example with these Mplus input files and data:
[https://www.statmodel.com/usersguide/chap6/ex6.16.html](url)
[https://www.statmodel.com/usersguide/chap6/ex6.16.dat](url)
```
test<-read.csv("ex6.16.dat.txt", header=FALSE, sep="")
as.data.frame(test)
names(test) <- c("x", "y1", "y2", "y3", "y4")

library(MplusAutomation)
testobject<-mplusObject(
  TITLE =	"this is an example of a two-part (semicontinuous) growth model for a
continuous outcome",
  
DATA = "",


DATA TWOPART = "
NAMES = y1-y4 ;
BINARY = bin1-bin4 ;
CONTINUOUS = cont1-cont4 ;",

VARIABLE =	"NAMES = x y1-y4 ;
USEVARIABLES = bin1-bin4 cont1-cont4 ;
CATEGORICAL = bin1-bin4 ;
MISSING = ALL(999) ;",

ANALYSIS =	"ESTIMATOR = MLR ;",
MODEL = "iu su | bin1@0 bin2@1 bin3@2 bin4@3 ;
iy sy | cont1@0 cont2@1 cont3@2 cont4@3 ;
su@0; iu WITH sy@0 ;)",

SAVEDATA = "
                         save = CPROBABILITIES;
                         file = test.dat ;", 
rdata = test)

testmodel <- mplusModeler(testobject, modelout = "test.inp", run = 1L)
```

This is the resulting error: 

```
+ DATA TWOPART = "
Error: unexpected symbol in:
"
DATA TWOPART"
```

Any help with this issue would be greatly appreciated! Thanks!

**Comment by cjvanlissa** [comment]
There is no 'DATA TWOPART' argument to the function mplusObject; type ?mplusObject to confirm this. Also, variable names in R cannot have spaces!

**Comment by cjvanlissa** [comment]
Addendum: Just put your code in the 'DATA' argument. If you look at the Mplus users' guide, you see that it is the same there.

**Comment by bew003** [comment]
Thank you! The way that the input file is written makes it seem like DATA TWOPART is a separate argument.
