### ISSUE TITLE
readModels cannot read Posterior Predictive P-Value in bayesian analysis

### ISSUE THREAD

**Issue by zhanglj37** [michaelhallquist/MplusAutomation#91]
Hi,

Thanks to the MplusAutomation package, it has facilitated my research. However, when I constructed Bayesian structural equation models, I found that the readModels function could not read the fitting index ppp value. I hope this can be improved in later versions.

Thanks!

**Comment by michaelhallquist** [comment]
Hi Zhang,

Have you looked at the "PostPred_PValue" field in $summaries? Here's what I see in one output:

```
BayesSummaries$summaries
  Mplus.version
1          6.12
                                                                      Title
1 this is an example of a path analysis with continuous dependent variables
  AnalysisType   DataType Estimator Observations NGroups NDependentVars
1      GENERAL INDIVIDUAL     BAYES          500       1              3
  NIndependentVars NContinuousLatentVars Parameters      DIC     pD
1                3                     0         15 4758.405 15.111
  ObsRepChiSqDiff_95CI_LB ObsRepChiSqDiff_95CI_UB PostPred_PValue
1                 -20.518                  16.484           0.642
          Filename
1 ex3.11_bayes.out
```

Please let me know if this what you're looking for.

Best,
Michael

**Comment by zhanglj37** [comment]
Hi Hallquist,

Thanks for your response! 
I'm sorry that this issue has not been fully expressed, this index cannot be find in the Monte Carlo simulation study:
`
$summaries
  Mplus.version
1             8
                                                                      Title
1 this is an example of a path analysis with continuous dependent variables
  AnalysisType   DataType Estimator NGroups NDependentVars NIndependentVars
1      MIXTURE MONTECARLO     BAYES       1             10                0
  NContinuousLatentVars NCategoricalLatentVars Parameters BIC_Mean BIC_SD
1                     1                      1         62 5029.703 91.041
  BIC_NumComputations DIC_Mean DIC_SD DIC_NumComputations pD_Mean pD_SD
1                 100 4815.366 90.939                 100   56.04 0.237
  pD_NumComputations       Filename
1                100 g2prior0.1.out

`
This index is above the DIC in the Mplus output:
`
MODEL FIT INFORMATION

Number of Free Parameters                       62

Bayesian Posterior Predictive Checking using Chi-Square

    Posterior Predictive P-Value

        Mean                                 0.492
        Std Dev                              0.224
        Number of successful computations      100

             Proportions
        Expected    Observed
           0.990       1.000
           0.980       1.000
           0.950       1.000
           0.900       1.000
           0.800       0.900
           0.700       0.800
           0.500       0.440
           0.300       0.220
           0.200       0.120
           0.100       0.030
           0.050       0.020
           0.020       0.010
           0.010       0.000

Information Criteria

    Deviance (DIC)

        Mean                              4815.366
        Std Dev                             90.939
        Number of successful computations      100

             Proportions                   Percentiles
        Expected    Observed         Expected       Observed
           0.990       0.990         4603.814       4536.051
           0.980       0.990         4628.604       4655.974
           0.950       0.950         4665.780       4664.868
           0.900       0.880         4698.818       4684.044
           0.800       0.810         4738.831       4735.391
           0.700       0.690         4767.677       4765.398
           0.500       0.520         4815.366       4819.291
           0.300       0.320         4863.055       4864.520
           0.200       0.230         4891.901       4896.923
           0.100       0.100         4931.914       4925.507
           0.050       0.030         4964.952       4956.380
           0.020       0.010         5002.128       4985.883
           0.010       0.000         5026.918       4992.326
`

Best,
Zhang

**Comment by michaelhallquist** [comment]
Hi Zhang,

It's possible that I inadvertently fixed this in recent months, but I'm unable to replicate this problem. Specifically, I see the posterior predictive p-values for Monte Carlo outputs. Attached is the output I used to validate the parser: 
[ex12.4_bayes.txt](https://github.com/michaelhallquist/MplusAutomation/files/4464746/ex12.4_bayes.txt).

The output of readModels on this file includes the posterior p-value information in $summaries:

```
     Title
1 this is an example of a Monte Carlo simulation study for a two-level growth model for a continuous outcome (three- level analysis)
  AnalysisType   DataType Estimator Observations NGroups NDependentVars NIndependentVars NContinuousLatentVars
1     TWOLEVEL MONTECARLO     BAYES         1000       1              4                2                     4

  Parameters PostPred_PValue_Mean PostPred_PValue_SD PostPred_PValue_NumComputations DIC_Mean  DIC_SD
1         16                0.486               0.09                             500 8791.228 121.022

  DIC_NumComputations pD_Mean pD_SD pD_NumComputations         Filename
1                 500 142.469 9.168                500 ex12.4_bayes.out
```

If you continue to have a problem, feel free to reopen the issue and upload a full .out file (rename as .txt for Github to accept it) so that I can test this.

Thanks,
Michael
