### ISSUE TITLE
Tech8 output

### ISSUE THREAD

**Issue by w-hardy** [michaelhallquist/MplusAutomation#92]
Hi, Mplus v8 computes PSR for prior-posterior predictive p (PPPp) values and model estimation, whereas v8 did not compute PPPp. When using the `model$tech8$psr` command a data frame of the iterations for computing the PPPp value is returned. Is it possible to have `model$tech8$psr_pppp` and `model$tech8$psr_model` separately?

I have attached an output file (as .txt) for further details.

Thanks

[6f 22i ads_ml_priors cr cl.txt](https://github.com/michaelhallquist/MplusAutomation/files/3226523/6f.22i.ads_ml_priors.cr.cl.txt)

**Comment by michaelhallquist** [comment]
Thanks for this note. The function now supports extraction of PPPP versus the model estimation. The former is `model$tech8$psr`, the latter is `model$tech8$psr_pppp`.

Best,
Michael
