### ISSUE TITLE
Problem with long var names differing in last characters

### ISSUE THREAD

**Issue by b1azk0** [michaelhallquist/MplusAutomation#93]
It looks like there is a problem with MplusAutomation needs to abbreviate variables to 8 characters, especially when as result non unique names appear.

My example is with a dataset that I reverse coded in some places . If the original item was called: `longitem15` and it's reverse version is stored as `longitem15r`, `mplusObject()` gives an error: `The following variables are not unique in the first 8 characters:`

Is there an easy way to fix this, considering I'd love the idea NOT TO rewrite all my syntaxes and variable naming schemas used by default in Qualtrics.

Thank you

**Comment by cjvanlissa** [comment]
There is no easy fix, this is an Mplus issue. Can you just rename the variables to X1-Xn before running estimate_profiles? You only need short variable names when passing to estimate_profiles.

**Comment by cjvanlissa** [comment]
This does not affect your naming in Qualtrics or anything.

**Comment by sda030** [comment]
I agree with van Lissa that this is a Mplus issue. It is also probably best to ensure good variable naming practices when data is being generated. I recommend using a separate prefix for all items in a latent variable to easily grab them as necessary.
Alternatively, as I do occasionally, is to rename temporarily to X1-Xn, and then rename back again when extracting from the model object (being very careful about correct renaming again).
Also suggest closing this issue.
