### ISSUE TITLE
prepareMplusdata with haven_labelled

### ISSUE THREAD

**Issue by gekess** [michaelhallquist/MplusAutomation#94]
Hello,

Are you thinking about integrating the use of tibbles with haven_labelled-variables in the function prepareMplusdata()?

Currently I get the error message:

> Error in .convertData(df) : 
> Currently only variables of class: 
> numeric, integer, logical, or factor
> but found additional class types including: 
> haven_labelled

The issue can be resolved by converting the data to integer. However, having this feature already included in the function would be nice!

And thanks for the great work so far!!

**Comment by JWiley** [comment]
@gekess could you post some R code that will make a haven_labelled class dataset? Should be easy enough to make preapreMplusData() compatible with it with an example.

**Comment by gekess** [comment]
Hi @JWiley 

thanks for coming back to me! Here is an example:

`install.packages("haven")
example <- haven::read_dta("https://stats.idre.ucla.edu/stat/stata/examples/ara/angell.dta")`

Is that sufficient?

Best
