### ISSUE TITLE
readModels doesn't extract residual matrices with invariance testing

### ISSUE THREAD

**Issue by gekess** [michaelhallquist/MplusAutomation#95]
Hello,

Information for the residual matrices in an Mplus-model with 
```
ANALYSIS:
model = configural metric scalar ; 
```
is not being extracted. This is a pity because the feature to extract information per group is extremely useful when comparing them. The residual matrix helps me to understand where the model implied covariance structure does not fit in the subsamples.

You can see for yourself with the following statmodel-example:
https://www.statmodel.com/usersguide/chap5/ex5.14.dat
https://www.statmodel.com/usersguide/chap5/ex5.14.inp 
Add to the ANALYSIS command the option:
`model = configural metric ; ! scalar not needed because of nomeanstructure`

After extracting the ex.15.4.out with readModels, the residuals-list is empty
`ex.5.14 <- readModels("/yourpath/ex.5.14.out)`
`ex.5.14$residuals`

Would be great to extract that kind of information!

**Comment by sda030** [comment]
I have problems extracting residuals for the simplest CFA model when using MLR (same model is fine with WLSMV). Mplus offers different residuals for MLR, with different header and layout than WLSMV so likely that.
[MLR_doesnt_work.txt](https://github.com/michaelhallquist/MplusAutomation/files/3482229/MLR_doesnt_work.txt)
[WLSMV_works.txt](https://github.com/michaelhallquist/MplusAutomation/files/3482230/WLSMV_works.txt)

**Comment by michaelhallquist** [comment]
The latest commit fixes residual extraction from invariance models. I have verified that it works well with the Holzinger-Swineford model/data. The problem with MLR residuals is important and unresolved, but it is a separate issue, so I will open a new issue about this.
