### ISSUE TITLE
error when load MplusAutomation

### ISSUE THREAD

**Issue by DongZhang1103** [michaelhallquist/MplusAutomation#99]
Hello,
     When I loaded the MplusAutomation pkage, error occured. 
"
     Error: package or namespace load failed for ‘MplusAutomation’ in rbind(info, getNamespaceInfo(env, "S3methods")):
 number of columns of matrices must match (see arg 2)
"    
     What's wrong? The R version I used is Microsoft R Open 3.5.3.

**Comment by michaelhallquist** [comment]
I don't believe this is an issue with the package. I've seen this sort of error more generally when you install a package under R 3.6, but then try to run it under R 3.5. I would check your sessionInfo(), make and make sure you install and run the package under the same version of R. If the issue persists, please post a reproducible example here, including your sessionInfo() output.

Michael

**Comment by DongZhang1103** [comment]
Thank you so much. I try it agian, but error is still . Following is my code.
-------------------
> library(MplusAutomation)
Error: package or namespace load failed for ‘MplusAutomation’ in rbind(info, getNamespaceInfo(env, "S3methods")):
 number of columns of matrices must match (see arg 2)
-----------------
